### ISSUE TITLE
Importing diffrax initializes Jax backend

### ISSUE THREAD

**Issue by brosand** [patrick-kidger/diffrax#106]
Importing diffrax for the first time initializes a jax backend per this [jax file](https://github.com/google/jax/blob/main/jax/_src/lib/xla_bridge.py). This raises a warning if there is no GPU on the machine, which can cause issues with a CI pipeline that uses Diffrax, as hiding this warning would prevent the warning from showing up later. Would there be an easy fix to stop this backend initialization when importing Diffrax? I don't know much about this level of the code.

**Comment by patrick-kidger** [comment]
So I think this should be fixed on main, but not yet pushed to PyPI. Can you install directly from GitHub and see if this resolves your issue? If it does then I'd be happy to do a new release ASAP.

**Comment by patrick-kidger** [comment]
New version should appear on PyPI in the next few hours, once the auto-deploy/test scripts have done their job.
