### ISSUE TITLE
Should `ts` in diffrax.StepTo be inclusive of `t0` and `t1`?

### ISSUE THREAD

**Issue by jatentaki** [patrick-kidger/diffrax#120]
I suppose not but it may be better to ask :)

**Comment by patrick-kidger** [comment]
`StepTo(ts=...)` should/must include `t0` and `t1` as passed to `diffeqsolve`.

(The error raised if you don't is here, incidentally:)

https://github.com/patrick-kidger/diffrax/blob/ebfa6a82b884f6f188e24f37a396d05bc3e06daa/diffrax/step_size_controller/constant.py#L122
