### ISSUE TITLE
Computing Jacobians of vector field

### ISSUE THREAD

**Issue by farhadnawaz** [patrick-kidger/diffrax#139]
Having defined a vector field $f_{\theta}(t, y)$ as in **class Func(eqx.Module)** in [neural_ode](https://github.com/patrick-kidger/diffrax/blob/main/examples/neural_ode.ipynb), I want to compute the jacobian $\frac{\partial f_{\theta}(t,y)}{\partial y}$ at different inputs $y$. Using jacfwd, I am able to compute $\frac{\partial f_{\theta}(t,y)}{\partial y}$ at one $y$, but not over multiple inputs. 

For example, if  $f_{\theta}(t, y)$ takes in $y$ as an argument with size $(2,)$, I want to compute the jacobians of 200 $y$'s which is given as $y.size = (200,2)$. Hence, the size of the jacobian I want is $(200,2,2)$. 

Should I go through a procedure similar to **exact_logp_wrapper** and **train** in **class CNF** in [CNF](https://github.com/patrick-kidger/diffrax/blob/main/examples/continuous_normalising_flow.ipynb)?

**Comment by patrick-kidger** [comment]
You should be able to do this via vmap. `jax.vmap(jax.jacfwd(fn))(x)` will compute a batch of Jacobians.

**Comment by farhadnawaz** [comment]
Thanks! How do yo extend to more dimensions? For example, if $y.shape = (32,200,2)$, then the size of jacobian should be $(32,200,2,2)$. I tried playing with **in_axes, out_axes** on vmap, but it doesn't seem to work.

**Comment by patrick-kidger** [comment]
`jax.vmap(jax.vmap(jax.jacfwd(fn)))(x)`?

**Comment by farhadnawaz** [comment]
Got it, thanks!
