### ISSUE TITLE
Add support for online settings

### ISSUE THREAD

**Issue by patrick-kidger** [patrick-kidger/diffrax#14]
This is relevant for CDEs in particular, but in principle one could also want to solve an ODE or SDE continuously as part of some larger program.

Related to #5?

**Comment by rubick1896** [comment]
Can you give a short example of how to do online prediction given a trained neural CDE with rectilinear interpolation?

**Comment by patrick-kidger** [comment]
You'd need to iteratively call the solver between the times you want predictions.

I'm afraid I don't have time to put something on that together, but I'd be happy to take a PR on this.

**Comment by rubick1896** [comment]
> Manually using the solvers directly (without diffeqsolve) is now documented.
Can you point out where this is documented specifically?

**Comment by patrick-kidger** [comment]
https://docs.kidger.site/diffrax/usage/manual-stepping/
