### ISSUE TITLE
Minor release for fixing the `tree_util` JAX warning?

### ISSUE THREAD

**Issue by DanPuzzuoli** [patrick-kidger/diffrax#140]
Hi @patrick-kidger !

Any chance you'd be willing to do a minor release of both diffrax and equinox to silence the new JAX `tree_util` warnings? (I see PRs have already been merged into the main of both for this.)

**Comment by patrick-kidger** [comment]
Sure thing. Equinox v0.6.0 and Diffrax v0.2.1 have just been released.
(Will now take a few hours for the bots to run tests and upload things.)

**Comment by DanPuzzuoli** [comment]
Awesome, thanks!
