### ISSUE TITLE
Still get warnings on `tree_util` 

### ISSUE THREAD

**Issue by JiaYaobo** [patrick-kidger/diffrax#146]
Hi @patrick-kidger ,
I find recent version of `diffrax` has updated to `jax 0.3.15`, but there's still a place you use `jax.tree_leaves` intead of `jtu.tree_leaves` in `diffax/misc/ad.py` in line 32 which leads to warnings, this is a small mistake, maybe u have noticed it. : )

**Comment by patrick-kidger** [comment]
Thanks for the heads-up. :) I've opened a PR to fix this.
