### ISSUE TITLE
Solving undertermined set of odes

### ISSUE THREAD

**Issue by thibmonsel** [patrick-kidger/diffrax#150]
Hi Patrick, 

I was wondering if with `diffeqsolve` it is possible to learn a set of undetermined odes. I suppose that is not the case since the input and output shape of what you feed your neural ode needs to be of equal size.

**Comment by patrick-kidger** [comment]
That's correct; `diffeqsolve` only handles fully-determined ODEs.

Underdetermined ODEs are a pretty niche thing; I don't think I know of any computational packages that handle this. (Do you?) I don't know of any way of determining the parametric solution set in general.

**Comment by thibmonsel** [comment]
Thanks again for the quick response ! I assume also that a delay differential equations aren't possible with ```diffeqsolve``` but could probably be incorporated somehow the [ddeint](https://fr.mathworks.com/help/matlab/math/delay-differential-equations.html) with ```diffrax``` ?

**Comment by patrick-kidger** [comment]
Yeah, there's no current support for DDE, but I'd be open to adding this if it can be done straightforwardly.
