### ISSUE TITLE
pjit-able

### ISSUE THREAD

**Issue by pharringtonp19** [patrick-kidger/diffrax#151]
**Question**: Is it possible to `pjit` across initial values in an ode?

**Context**:
I am able to `vmap` across an array of initial values but I am unable to `pjit` across the same initial values. 

When I try to pjit across the initial values I get the following:
```
2022-08-24 14:11:45.268976: F external/org_tensorflow/tensorflow/compiler/xla/service/hlo_sharding.cc:802] Check failed: IsTuple() 
Aborted (core dumped)
```

The following is my best attempt at a MWE given that the pjit application will depend on the compute resources one has access to

```
from diffrax import diffeqsolve, ODETerm, Dopri5
import jax.numpy as jnp
import jax 
from rfp import pjit_time_grad

def f(t, y, args):
    return -y

term = ODETerm(f)
solver = Dopri5()
y0 = jax.random.normal(jax.random.PRNGKey(0), shape=(8, 2))

def f(y0):  
    solution = diffeqsolve(term, solver, t0=0, t1=1, dt0=0.1, y0=y0).ys
    return solution

print(jax.vmap(f)(y0).shape)
pjit_func(f, y0) # User implemented
```

**Comment by patrick-kidger** [comment]
It certainly should be possible to `pjit` across initial values. Diffrax and `pjit` do pretty much orthogonal things.

Unfortunately your MWE isn't runnable. Both `rfp` and `pjit_func` are undefined. Can you put together a MWE that I can run that will demonstrate the issue?

(Preferably on the CPU only. If you want to have multiple devices then you can do this by adding e.g. `os.environ['XLA_FLAGS'] = '--xla_force_host_platform_device_count=4'` right at the top of your script, before you `import jax` or `import diffrax`.)

**Comment by pharringtonp19** [comment]
@patrick-kidger Thanks for the response.

Based on https://github.com/google/jax/issues/7931, I'm not sure if we can run pjit on cpus, so for the moment I've run it with gpus (happy to change it to cpus if I'm wrong though!)

Below is a MWE -- Thanks
```
import jax 
import jax.numpy as jnp 
from jax.experimental import maps 
from jax.experimental import PartitionSpec 
from jax.experimental.pjit import pjit 
import numpy as np 
from diffrax import diffeqsolve, ODETerm, Dopri5


print(jax.devices())
print(jax.devices('cpu'))
mesh_shape = (4,)
devices = np.array(jax.devices()).reshape(*mesh_shape)
mesh = maps.Mesh(devices, ('x',))
print(mesh)

def vector_field(t, y, args):
    return -y

term = ODETerm(vector_field)
solver = Dopri5()
input_data = np.arange(8 * 2).reshape(8, 2).astype(jnp.float32)

def ivp(y0):  
    solution = diffeqsolve(term, solver, t0=0, t1=1, dt0=0.1, y0=y0).ys
    return solution

print(jax.vmap(ivp)(input_data).shape)

f = pjit(
  lambda data: jax.vmap(ivp)(data),
  in_axis_resources=PartitionSpec('x',),
  out_axis_resources=PartitionSpec('x',))
 
#Sends data to accelerators based on partition_spec
with maps.Mesh(mesh.devices, mesh.axis_names):
    data = f(input_data)
print(type(data))
```

Error
```
2022-08-30 13:14:29.153620: F external/org_tensorflow/tensorflow/compiler/xla/service/hlo_sharding.cc:802] Check failed: IsTuple() 
Aborted (core dumped)
```

**Comment by patrick-kidger** [comment]
Just getting back around to this now; sorry for the delay.

When I try running your example on my single-GPU machine (with `mesh_shape = (1,)`) I actually get a different error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/jax/_src/util.py", line 255, in remove_key
  File "/opt/conda/lib/python3.7/site-packages/jax/experimental/pjit.py", line 849, in __hash__
  File "/opt/conda/lib/python3.7/site-packages/jax/experimental/pjit.py", line 849, in <genexpr>
  File "/opt/conda/lib/python3.7/site-packages/jax/experimental/sharding.py", line 337, in _op_sharding_hash
  File "/opt/conda/lib/python3.7/site-packages/jax/experimental/sharding.py", line 320, in _hash_op_sharding
AttributeError: 'NoneType' object has no attribute 'Type'
```

But surprisingly: running this as `ipython script.py` rather than `python script.py`, then things work!

I'm not familiar with the internals of `pjit`, so I'm afraid I don't know why it's failing in two different ways for us, or why `ipython` works when `python` doesn't. I'd suggest raising this as an issue over on the JAX repo and see what they say.

**Comment by pharringtonp19** [comment]
@patrick-kidger Absolutely no worries -- Thanks for taking a look at this! I'll close for now and reopen if I figure out the reason for the differences
