### ISSUE TITLE
Save and load trained model

### ISSUE THREAD

**Issue by farhadnawaz** [patrick-kidger/diffrax#153]
How can I save and load a trained neuralODE model using JAX? For example, in [neural_ode](https://github.com/patrick-kidger/diffrax/blob/main/examples/neural_ode.ipynb), how can I save **model** and load it for future use? How can I get the parameters (weights, biases, etc) of the trained **model**?  Is there an equivalent to [this](https://pytorch.org/tutorials/beginner/saving_loading_models.html) for JAX/equinox models?

**Comment by patrick-kidger** [comment]
Yep! Diffrax builds on top of Equinox, which has [support for serialisation](https://docs.kidger.site/equinox/api/utilities/serialisation/).

**Comment by ameya98** [comment]
I think https://docs.kidger.site/equinox/api/serialisation/ is the right link!

**Comment by farhadnawaz** [comment]
Thanks!
