### ISSUE TITLE
RHS for continuous time D-Control

### ISSUE THREAD

**Issue by SimiPixel** [patrick-kidger/diffrax#155]
Hello Patrick, 

i would like to create a feedback controlled differential equation. However, i do not know how to create the D-Controller. I can just "imagine" how to build it in an explicit euler scheme, i.e. thinking about it in a discrete step-function sense.
I was thinking something like this:

```python
dim = 3

def gen_y0():
    return jnp.zeros((dim))

def rhs(t,y,args):
    # some reference ..
    r = 0.1 
    # .. some time-varying error as a function of reference
    e = r - t 
    
    delayed_t = y[0] # ?? I don't know how to handle this / get a delayed time
    dt = (t - delayed_t)
    delayed_e = (y[1] - y[2]) / dt 

    D = (e - delayed_e) / dt

    return jnp.array([
        1.0,
        e, 
        delayed_e,
    ]) 

term = dfx.ODETerm(rhs)
saveat = dfx.SaveAt(ts=jnp.arange(11)/10.0)

dfx.diffeqsolve(term, Euler(), t0=0, t1=1.0, y0=gen_y0(), dt0=0.1, saveat=saveat).ys

```

Do you happen to have any insights into this? What am i missing?
Thank you in advance!

**Comment by SimiPixel** [comment]
After some thoughts, i think i have to re-write my system with state dimension $n$, number of inputs $m$, number of measurements $p$ as 
$$(\mathbb{1}+B K_d C) \frac{dx}{dt}=f(x) + B K_d \frac{dr}{dt}$$
where $B \in \mathbb{R}^{n\times m}, K_d \in \mathbb{R}^{m\times p}, C \in \mathbb{R}^{p\times n}$ and $r(t) \in \mathbb{R}^p$  is the time-varying reference.

**Comment by patrick-kidger** [comment]
Something like that looks correct. The continuous-time form of a D-controller uses the derivative. (In particular you don't need to turn this into a delay diffeq.)

See e.g. the "mathematical form" heading on [its Wikipedia page](https://en.wikipedia.org/wiki/PID_controller).
