### ISSUE TITLE
NewtonNonLinearSolver not sure if its intended

### ISSUE THREAD

**Issue by thibmonsel** [patrick-kidger/diffrax#158]
Hello Patrick !

I have been playing around with the Newton Raphson solver. It works great for functions f that have matching dimensions for its output and input, thanks for that ! 

However im trying out a function that goes from R to R^2 and get some error. 
I was wondering if the solver only works for function that have the same input and output dimension.

Workable example of what i have is : 
```
alpha_fn = lambda t, args: jnp.array([t - 2, t - 2.1])
root_solver = diffrax.NewtonNonlinearSolver(atol=10e-3, rtol=10e-6, max_steps=10)
root_solver(alpha_fn, 1.9 ,None)
```
The error yielded comes from jax's linalg solver.

**Comment by patrick-kidger** [comment]
You closed this, but to comment on this a bit further: yes, this is intended. Most texts will tell you that it's only considered to be a well-defined problem if it has the same input and output dimensionality.

In practice this can be generalised (and I have some in-progress work to accomplish this) but that's a little esoteric.

**Comment by thibmonsel** [comment]
I convinced myself that the dimensions should match. Looking forward to see your work in progress !
