### ISSUE TITLE
How do you fix `max_steps` of adaptive solver ?

### ISSUE THREAD

**Issue by pablo2909** [patrick-kidger/diffrax#161]
Hello,

I am trying to understand the inner workings of the code, more specifically how you handle the maximum number of steps in a bounded while loop for an adaptive solver.
I understand that you bound the number of step with the length of the time array, hence: `max_step = int((t1-t0)/min_step_size)` 
https://github.com/patrick-kidger/diffrax/blob/2c538af25d403d64df0361e254e85a85fed71246/diffrax/integrate.py#L311

Is my understanding correct ? That this is the maximum number of steps that can be performed ?

If yes, why is this the case ? I don't know what the right upper bound is, but I can imagine that this one might not work. For example if many steps are rejected, we could require more steps than `max_step`.

Thank you very much for any input ! 
Best

**Comment by patrick-kidger** [comment]
Hey there. So the code you've highlighted actually does something else: this part is just about saving the output of the model, and is unrelated to the number of integration steps taken.

The actual maximum number of integration steps is the value passed as `diffeqsolve(..., max_steps=...)`. By default this is 4096, but you can change this value.

As a general rule you should use the smallest value of `max_steps` that works for your problem. For technical reasons, the cost of the differential equation solve increases every time `max_steps` passes a power of 16. The default 4096=16^3. (If you want you can also pass `max_steps=None`, but this disables backpropagation.)

Does that make sense?

**Comment by pablo2909** [comment]
> Hey there. So the code you've highlighted actually does something else: this part is just about saving the output of the model, and is unrelated to the number of integration steps taken.

Oops ok , thanks for the clarification ! 

> Does that make sense?

It does, thank you ! 

I have a follow up question if that's ok. In the case of `DiscretiseThenOptimise`, for an adaptive solver, you use a bounded while loop that you bound with 4096 by default (the `maxstep` value passed in `diffeqsolve`).
And for the case of `OptimiseThenDiscretise`, how do you do it exactly ? Do you also use a bounded while loop ? I would say there is no need to bound the loop since we are already defining the backward in the `vjp`. But it would definitely be useful to bound it and have some guarantee on the execution time, no ? I admit I am a bit confused here.  

Thank you very much for the help :)

**Comment by patrick-kidger** [comment]
When using optimise-then-discretise. From an algorithmic standpoint, we use a while loop that may or may not have a bound, depending on whether or not `max_steps=None` or `max_steps=<some integer>`. So indeed the bound isn't necessary, but nonetheless the `max_steps` setting is respected if it passed.

From a JAX-code-standpoint, we use a `jax.lax.while_loop`, rather than a `diffrax.misc.bounded_while_loop`. (With a max step condition if necessary.) Since reverse-mode autodifferentiation directly through the loop isn't required, then compilation is more efficient using a plain `while_loop`.

**Comment by pablo2909** [comment]
Understood ! Thanks a lot for the clarification !
