### ISSUE TITLE
Distributional PDE

### ISSUE THREAD

**Issue by krzysztofrusek** [patrick-kidger/diffrax#177]
According to [presentation](https://web.stanford.edu/~yamins/uploads/2/4/9/2/24920889/presentation.pdf)

> The GRAND PRINCIPLE: non-deterministic trajectories
> generated by statistical differential equations should be
> governed by a deterministic PDE on the probability density of
> states.

Are there any plans for this in diffrax ?

**Comment by patrick-kidger** [comment]
You've mentioned both SDEs and PDEs.

Diffrax supports SDEs already.

Many kinds of PDEs are also supported: those that can be reduced to ODEs/SDEs, e.g. via method of lines.

(And in fact the idea you've highlighted actually also leads to numerical methods for some PDEs, by drawing many samples from their equivalent SDE.)

Beyond that no special support is planned: the scope of Diffrax is finite-difference methods for ODEs/SDEs/CDEs.

**Comment by krzysztofrusek** [comment]
Thanks for clarification
