### ISSUE TITLE
Defining a time-varying vector field with a specific structure? 

### ISSUE THREAD

**Issue by birajpandey** [patrick-kidger/diffrax#178]
I wanted to know how to define a time-varying vector field with a specific structure. For instance, let $y \in R^{n \times 1}$. Our vector field has the following structure. 

$\dfrac{dy}{dt} (t) = f(t, y(t); A(t)) = A(t) K(y(t)) $  

where, 
$A(t) \in \mathbb{R}^{n \times m}$ are learnable parameters and vary with time and  $K(y(t)) \in \mathbb{R}^{m \times 1}$ doesn't depend on time. Given some data, I want to learn A(t).  

I can think of implementing this as a ResNet with the euler discretization and learning $A(t)$. But I was wondering if there's a simpler way to implement such an ODE in diffrax. 

Such a vector field was straightforward to implement when $A$ doesn't change with time. But the time-varying case was confusing. I tried looking at the implemented examples and perhaps Neural CDE is relevant? I'm not sure. Any of your suggestion is appreciated! I can provide my implementation of the time-independent implementation if that gives more context.

**Comment by patrick-kidger** [comment]
Right, so time-varying parameters are quite a standard thing to do.


You have two possible approaches. First, it's quite common for `A(t)` to itself be defined by an ODE. In this case, you can convert:
```
dy/dt = f(y(t), A(t))
```
into:
```
dy/dt = f(t, y(t), A(t))
dA/dt = g(t, A(t), θ)
```
and solve the ODE with respect to both `y` and `A` jointly, with parameters `θ`.

If A isn't defined by an ODE, but is described directly by some function `A(t) = α(t, θ)`, once again with "meta-parameters" `θ`, then it's also doable: write it as the ODE
```
dy/dt = h(t, y(t), θ)
```
where
```
h(t, y, θ) = f(t, y, α(t, θ))
```

In either case: you make some choice on how to paramaterise `A` by `θ`. Then as far as the code is concerned, you treat `θ` as your parameters throughout.

See also [Section 2.3.2 of On Neural Differential Equations](https://arxiv.org/abs/2202.02435), which discusses some of the modeling options here in more detail.

**Comment by birajpandey** [comment]
Thanks for the quick reply! This answers my question exactly. Will follow up if I have any questions.
