### ISSUE TITLE
Make brownian motion path classes accept shape: PyTree[Tuple[int]]

### ISSUE THREAD

**Issue by ciupakabra** [patrick-kidger/diffrax#180]
Suppose we want to integrate the following SDE ( $X_t$ is $2d$ dimensional)

$$
dX_t = f(X_t, t)\mathrm{d}t + 
\begin{pmatrix} 
    0_{d \times d}\\
    1_{d \times d}
\end{pmatrix}\mathrm{d}W_t
$$

For the diffusion term it would be wasteful to use the full `diffrax.ControlTerm` term, instead we'd like to make use of `diffrax.WeaklyDiagonalControlTerm`. `diffrax.WeaklyDiagonalControlTerm` allows our vector fields and control paths to output PyTrees, so we could start by defining `vector_field = lambda _ : (jnp.zeros(d), jnp.ones(d))`. However, correct me if I'm wrong but at the moment there's no clean way to create a Brownian path which outputs PyTrees, since `diffrax.VirtualBrownianTree` accepts the argument `shape` only as a `Tuple[int]`. I see no reason why it couldn't be `PyTree[Tuple[int]]`, which allows much more freedom modelling the diffusion term efficiently.

Since it seems to be quite a small change I'm happy to write a PR for this, if the authors like the suggestion.

**Comment by patrick-kidger** [comment]
Yep, that makes sense to me. A PR would be welcomed.

I think `shape` should probably be of type `Union[Tuple[int, ...], PyTree[jax.ShapeDtypeStruct]]`. This would additionally allow for specifying dtype if required.

**Comment by patrick-kidger** [comment]
Closing as now implemented in Diffrax 0.2.2.
