### ISSUE TITLE
Support for regularizing error estimates?

### ISSUE THREAD

**Issue by jaschau** [patrick-kidger/diffrax#196]
Hi,
I was wondering if it is possible in Diffrax to use the solver's error estimates for regularizing a Neural ODE during training, i.e., implement the method https://arxiv.org/abs/2105.03918 mentioned in section 5.4.2.3 of the thesis "On neural differential equations" https://arxiv.org/abs/2202.02435.
I guess there are two sides to my question. The first being if it's possible at all given possible Jax limitations and the second one being how I can obtain these error estimates from a solve's `Solution` object,
I'd be grateful for any pointers!

**Comment by patrick-kidger** [comment]
This kind of thing should be doable like so:
```python
import diffrax as dfx
from equinox.internal import ω

class MySolver(dfx.AbstractSolver):
  solver: dfx.AbstractSolver

  def init(...):
    state = self.solver.init(...)
    return state, 0.0

  def step(self, ..., t0, t1, state):
    state, penalty = state
    ..., y_error, state = self.solver.step(..., state)
    penalty = (ω(penalty) + (t1 - t0) * ω(y_error).call(jnp.abs)).ω
  return ..., y_error, (state, penalty)

  ... # forward all other relevant methods

sol = dfx.diffeqsolve(MySolver(...), ..., saveat=SaveAt(..., solver_state=True))
_, penalty = sol.solver_state
```
You could also put this in `controller_state` instead if you preferred.

**Comment by jaschau** [comment]
Wow, excellent! That looks like an elegant solution :) I'll give this a shot and report back if I encounter any issues. Do you think that would be interesting as an example if we manage to reproduce, e.g., the MNIST experiments from the paper?

**Comment by patrick-kidger** [comment]
Overall, I think I probably wouldn't include the above as an example. I think the relatively-small changes above would probably get lost in the rest of the code for training/evaluation etc.

Still, I appreciate you asking. I am generally in favour of adding more examples.

**Comment by jaschau** [comment]
That's a completely valid point. I still need to figure out anyways if the proposed technique speeds up training for my use-case :).
