### ISSUE TITLE
Fastest way to evaluate a solution

### ISSUE THREAD

**Issue by marcofrancis** [patrick-kidger/diffrax#203]
Hi,
suppose I have a simple ODE that I solve with diffrax. What would be the fastest way to use the solution in another piece of code?
I need to evaluate the solution on some points not known in advance, and I thought of generating a dense solution `sol` and then use its method `evaluate` on the points of interest, i.e. every time I need it, call `sol.evaluate()` on my points of interest (using `vmap` when needed). Is this the most efficient way, or shall I interpolate myself a fixed grid solution and create a jitted function that evaluates it on my points of interest?

**Comment by patrick-kidger** [comment]
Dense output is probably what you want here! `sol.evaluate` is fast to evaluate. Internally it does pretty much what you describe: just evaluating an interpolation over the solution that was obtained at grid points.

**Comment by marcofrancis** [comment]
Thanks! Somehow I forgot to reply, sorry.
