### ISSUE TITLE
Slope is negative everywhere, but diffrax integrates to a positive value

### ISSUE THREAD

**Issue by samuela** [patrick-kidger/diffrax#208]
An ODE I am integrating has a value with negative slope everywhere (confirmed via logging), and yet diffrax integrates to a positive value when starting with y0=0. Similarly, when solving backwards in time it integrates to a negative value when the solution is necessarily positive. I have confirmed this phenomenon with multiple solvers (Tsit5, Dopri5), and multiple `stepsize_controller`s.

I have put together a [small reproduction in a Colab](https://colab.research.google.com/drive/1rLkRK3rldmowKf4_6qEV2h4YD1dkk-mG?usp=sharing). Tested on `diffrax==0.2.2`, the latest release on PyPI at the time of writing.

Any idea what could be producing this kind of errant behavior?

**Comment by samuela** [comment]
Actually, I believe that this is due to `dt0` being too aggressive. I'm going to close this for now...

**Comment by samuela** [comment]
Actually I'm still not sure I understand how the result can be positive after all the dynamics evaluations are negative... maybe an overflow of some sort?

**Comment by patrick-kidger** [comment]
I've not dug into your example (I can take a look if you think that'll help), but it is possible to have negative numerical solutions given only positive vector field evaluations. This is because the Butcher tableau can contain negative entries.

See also #200 for ways to enforce positivity.

**Comment by samuela** [comment]
Thanks for explaining @patrick-kidger, I'll give the ideas in #200 a shot!
