### ISSUE TITLE
ODE solvers corresponding to RK4

### ISSUE THREAD

**Issue by mstoelzle** [patrick-kidger/diffrax#240]
Hi Patrick,

Thanks for creating this great library!

Are there any explicit ODE solvers included, which correspond to RK4 / "the Runga-Kutta method"? https://en.wikipedia.org/wiki/Runge–Kutta_methods

If not, is there a reason it has not been implemented?  Could I contribute it as a PR?

Best regards,

Maximilian

**Comment by patrick-kidger** [comment]
I wouldn't describe RK4 as "**the** Runge-Kutta method". (Never mind what Wikipedia says!) Diffrax implements most of the useful lower-order Runge-Kutta solvers.

RK4 specifically isn't implemented. I'm honestly not sure how useful it still is these days -- I suspect most problems it is appropriate for are probably better handled either by going up to `Tsit5` or down `Bosh3`, and e.g. it doesn't even get mentioned in this literature review from 2016: 

https://github.com/SciML/DiffEqDevDocs.jl/blob/78c80e117a0da0ebadd7d064a77860c01d371540/docs/src/internals/notes_on_algorithms.md

That said, I've not benchmarked it myself. I'd be happy to take a pull request implementing it if it's something you particularly want.

**Comment by mstoelzle** [comment]
Thanks Patrick for your quick response and the reference to this literature review. I will try some of the already implemented solvers first and if I encounter a need for `RK4`, I will try to contribute that as a PR.
