### ISSUE TITLE
Using Diffrax with Sympy2Jax

### ISSUE THREAD

**Issue by JR-1991** [patrick-kidger/diffrax#248]
First of all, many kudos to your work on neural ODEs and Diffrax - I enjoyed reading your thesis and diffrax quite a lot 🎉

I am currently implementing a framework to integrate and optimize enzyme kinetic models and for this I wanted to make use of `Sympy2Jax`. The aim is to let users (experimentalists, modellers) pass their equations as a string, which are then converted to JAX functions and fed into various methods for analysis and parameter estimation.

So far I am struggling to make it work without explicitly writing a wrapper to accommodate for the conversion of positional arguments to keyword arguments. In the following is a working hard-coded example:

```python
vector_field = SymbolicModule(sympify("- k1 * y + k2"))

def wrapped(t, y, params):
  """Wrapper function to accomodate for args to kwargs"""

  k1, k2 = params

  return vector_field(y=y, k1=k1, k2=k2)

term = ODETerm(wrapped)
solver = Dopri5()
saveat = SaveAt(ts=[0., 1., 2., 3.])
stepsize_controller = PIDController(rtol=1e-5, atol=1e-5)

params = (10.0, 20.0,)

sol = diffeqsolve(term, solver, t0=0, t1=3, dt0=0.1, y0=1, args=params, saveat=saveat,
                  stepsize_controller=stepsize_controller)
```

Is there a way to work around this and supply dynamic unpacking of `params` to facilitate `jax.jit`? Maybe I am missing something, that's why I wanted to ask if there is already a solution present. I am also quite new to JAX, maybe there is already something that solves it.

Thanks in advance and keep up the great work! 🙂

**Comment by patrick-kidger** [comment]
Thank you! I'm glad to hear you like sob midi of my work.

> So far I am struggling to make it work without explicitly writing a wrapper to accommodate for the conversion of positional arguments to keyword arguments.

This is expected behaviour. It's generally pretty common to write small wrappers like this when writing JAX code.

In terms of handling this one: you could make your params be a dictionary. (Any pytree will do.) That is to say:
```python
vector_field = SymbolicModule(sympify(...))

def wrapped(t, y, params):
  return vector_field(y=y, **params)

term = ODETerm(wrapped)
params = dict(k1=..., k2=...)
```
In which case an end user can input both the equation string and the `params` together, and the wrapper doesn't need to know about exactly what was passed.

Does that help?

**Comment by JR-1991** [comment]
That's awesome! Thanks a lot, solved it for me 🙌
