### ISSUE TITLE
Is there a way to extract values from inside vector_field?

### ISSUE THREAD

**Issue by fhchl** [patrick-kidger/diffrax#255]
Let's say I want to simulate a simple feedback system $\dot x = f(x, u), u = K x$. Is there a way to save $u$ 
together with the states $x$? Right now I am computing $u$ again after solving the ODE.

 I have seen `SaveAt`'s `fn` argument, so one could in principle recompute $u$ in there, but then again, one computes $u$ twice.

In my a bit more involved use case, computing $u$ is not a super cheap operation that I'd like to avoid running twice.

**Comment by fhchl** [comment]
Yes, $K$ is a matrix. If it was a function $u = v(x)$, one could $\dot u = \partial v/\partial x \cdot \dot x$ and then integrate that - true!

It would be great to have the option to let `vector_field` return an auxiliary value a la `(x_dot, aux)`, which could be accessed as `solution.aux`.

```python
def vector_field(t, y, args):
    x, _ = y
    u = K @ x
    x_dot = f(x, u)
    return x_dot, u

term = ODETerm(vector_field)
solution = diffeqsolve(term, ..., has_aux=True)
xs = solution.ys
us = solution.aux
```

If this is not too niche, I could try and give it a go - maybe with the help of some guidance.

**Comment by fhchl** [comment]
Sorry for the confusion! I made a mistake there -.-

What I meant to write was

```python
def vector_field(t, x, args):
    u = K @ x
    x_dot = f(x, u)
    return x_dot, u
```

**Comment by patrick-kidger** [comment]
Okay! So you are defining $u(t) = K x(t)$. In that case, what $t$-value are you looking to evaluate $u(t)$  at?

I would note that a differential equation solver will evaluate your vector field many times -- if need be, then the cost of evaluating `K @ x` once more should be negligible compared to the number of times it has already been performed inside the diffeqsolve.

**Comment by fhchl** [comment]
I was looking to evaluate $u(t)$ at the same points as $x(t)$ at equidistant samples at a high samplerate (I am working in with audio).

> I would note that a differential equation solver will evaluate your vector field many times -- if need be, then the cost of evaluating K @ x once more should be negligible compared to the number of times it has already been performed inside the diffeqsolve.

I was totally missing that. It's a great good point. Tested it with this small script:

```python
from diffrax import diffeqsolve, ODETerm, Dopri5, SaveAt
import jax.numpy as jnp
from jax import jit, vmap
import time
import equinox as eqx
import jax

key = jax.random.PRNGKey(21)
mlp = eqx.nn.MLP(in_size=4, out_size=4, width_size=100, depth=10, key=key)

def feedback(y):
  return mlp(y)

def f(t, y, args):
    u = feedback(y)
    return -y + u

y0 = jnp.array([1., 2., 3., 4.])
ts = jnp.arange(0, 1, 1/20000)
term = ODETerm(f)
solver = Dopri5()
saveat = SaveAt(ts=ts)
dt0 = ts[1]

def benchmark(fun, n=10):
  fun()
  start = time.perf_counter()
  for i in range(n):
    fun()
  print(fun.__name__, (time.perf_counter() - start)/n)

@jit
def pure_solve():
    sol = diffeqsolve(term, solver, t0=0, t1=1, dt0=dt0, y0=y0, saveat=saveat, max_steps=len(ts)*50)
    ys = sol.ys
    return ys

@jit
def solve_with_output():
    sol = diffeqsolve(term, solver, t0=0, t1=1, dt0=dt0, y0=y0, saveat=saveat, max_steps=len(ts)*50)
    ys = sol.ys
    return vmap(feedback)(ys)

benchmark(pure_solve)
benchmark(solve_with_output)
```

which returns

```
pure_solve 0.6017862516000605
solve_with_output 0.6039610730000277
```

so indeed, the additional computation is negligible in comparison to solving the ODE. Thanks for the insight!
