### ISSUE TITLE
Help with Discrete Event Handling

### ISSUE THREAD

**Issue by snehjp2** [patrick-kidger/diffrax#262]
Hello! Great work here -- I am really enjoying this library and finding it very quick in solving some otherwise difficult to solve stiff ODEs. I'm wondering if I can get some clarity on event handling:
`

          def boltzmann_eq(t, y, args):
              H, Omega = y[0], y[1:]
              Omega_m = jnp.sum(Omega)
              dH_dt = (-1 / 2) * H ** 2 * (4 - Omega_m)
              dOmega_dt = H * Omega - self.Gamma_0 * Omega - H * Omega * Omega_m

              return jnp.concatenate((jnp.array([dH_dt]), jnp.array(dOmega_dt)))
          
          def condition_fn(sol):
              Omega_m = jnp.sum(sol.ys[1:])
              if Omega_m < self.Omega_m_min:
                  return True

          self.t_eval = self.t_eval.astype(jnp.float64)
          self.Gamma_0 = self.Gamma_0.astype(jnp.float64)
          
          term = ODETerm(boltzmann_eq)
          solver = Kvaerno5()
          saveat = SaveAt(ts=self.t_eval)
          stepsize_controller = PIDController(rtol=1e-8, atol=1e-8)
          event = DiscreteTerminatingEvent(cond_fn=condition_fn)
          
          @jit
          def return_sol():
              sol = diffeqsolve(term, 
                              solver, 
                              t0=self.t_eval[0], 
                              t1=self.t_eval[-1], 
                              dt0=0.1, 
                              y0=jnp.array(self.y0, dtype=jnp.float64), 
                              args=(self.Gamma_0,), 
                              max_steps=None, 
                              saveat=saveat,
                              stepsize_controller=stepsize_controller,
                              discrete_terminating_event=event)
              return sol
                
This code is solving Boltzmann equations from cosmology. Essentially there are N coupled ODEs, and I would like to enforce that the solver stops once the sum of the solutions is less than some critical value. My current implementation breaks with the error:

`TypeError: condition_fn() got an unexpected keyword argument 'solver'`

Surely it's an issue of syntax that I'm missing -- I'm quite new to jax / diffrax as well as solving numerical ODEs, so any help is appreciated!

**Comment by patrick-kidger** [comment]
You probably want:
```python
def condition_fn(state, **kwargs):
    del kwargs
    Omega_m = jnp.sum(state.y[1:])
    ...
```

The reason is that `condition_fn` is called with a lot of information -- the call site is [here](https://github.com/patrick-kidger/diffrax/blob/7b875226a62522f9a06ee69e29486f3727a2b970/diffrax/integrate.py#L380) -- and the error you're getting is due to all that extra stuff being passed.
