### ISSUE TITLE
Basic Vmap Bug

### ISSUE THREAD

**Issue by DruvPai** [patrick-kidger/diffrax#267]
Hi, I'm having trouble seeing how the following MWE errors:

```py
import jax
from jax import numpy as jnp
from diffrax import diffeqsolve, ControlTerm, Euler, MultiTerm, ODETerm, SaveAt, VirtualBrownianTree

B = 20
D = 5

tol = 1e-3
dt0 = 0.05
T0 = 0.0
Tf = 1.0

def f(x0, key):
    drift = lambda t, x, args: jnp.zeros((D, ))
    diffusion = lambda t, x, args: jnp.zeros((D, D))
    brownian_motion = VirtualBrownianTree(T0, Tf, tol=tol, shape=x0.shape, key=key)
    terms = MultiTerm(ODETerm(drift), ControlTerm(diffusion, brownian_motion))
    solver = Euler()
    saveat = SaveAt(dense=True)
    sol = diffeqsolve(terms, solver, T0, Tf, dt0=dt0, y0=x0, saveat=saveat)
    return sol.evaluate(Tf)

x0 = jnp.zeros((D, ))
key = jax.random.key(1)
print(f(x0, key))

x0 = jnp.zeros((B, D))
key = jax.random.split(key, B)
print(jax.vmap(f)(x0, key))
```
In particular, the last three lines (with `vmap`) cause an error, while the previous three lines seem to work fine. Here are some observations from testing:
- From what I can tell, the `diffeqsolve` line may be where the error occurs, as if I remove the last two lines of the function then both tests work.
- The issue may be to do with the stochastic aspect of the SDE, since if I replace `terms` with just `ODETerm(drift)` then the `vmap` works. Also, modifying the controlled ODE at [https://docs.kidger.site/diffrax/usage/getting-started/](this page) to add a `vmap` works as intended.

My understanding (as a relative newcomer to Jax) is that `vmap` turns a function `f` with signature `(D, ) x () -> (D, )` into a function `g` with signature `(B, D) x (B, ) -> (B, D)`, assuming that each part is `vmap`pable. Please let me know if this is wrong.

Thanks, and please let me know if you need more details!

**Comment by patrick-kidger** [comment]
Hi! What error are you seeing? When I run your code snippet I get the following output:
```python
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
```
which I believe is what's expected.

**Comment by DruvPai** [comment]
Thanks for the quick reply! Here is the [stack trace](https://pastebin.com/46hbkCKb).
I now suspect this is a versioning issue: the output of my `conda list` is [here](https://pastebin.com/3xjrfYYz).

**Comment by patrick-kidger** [comment]
Ah, it looks like this specifically happens when you switch on the new PRNG (via `JAX_ENABLE_CUSTOM_PRNG=1`).

File a bug with your MWE against JAX itself --  this looks like an upstream issue.
