### ISSUE TITLE
`inf` filtering in diffrax solutions

### ISSUE THREAD

**Issue by snehjp2** [patrick-kidger/diffrax#286]
Hello! I have some equations I'm solving with the following parameters:

```
equation = ODETerm(boltzmann_eq)
solver = Kvaerno5()
saveat = SaveAt(ts=t_eval)
stepsize_controller = PIDController(rtol=1e-8, atol=1e-8)
event = DiscreteTerminatingEvent(cond_fn=condition_fn)
```

and here is the code where the solver is called:

```
t_eval = jnp.exp(jnp.linspace(0, 200, 2000))
sol = diffeqsolve(equation, solver, t0=t_eval[0], t1=t_eval[-1], dt0=0.01, y0=y0,
                      args=(Gamma_0,), max_steps=int(1e5), saveat=saveat,
                      stepsize_controller=stepsize_controller, discrete_terminating_event=event)
```

I have been reading about how diffrax handles values in `sol.ts` by filling them with `inf` in the event that the solver terminates before `t1`. I have previously used some boolean masking to remove these values, however I am now using this code within numpyro, and numpyro does not like the use of boolean masking to remove the `inf` values. The other option is substituting the `inf` values with 0.0, for example. However, I am extracting some statistics from the diffeq output, and the substitution with 0.0 values is not something that would work for my implementation. 

I'm wondering if there are any ideas on how to deal with the `inf` values, and removing them in a way that is jit / vmap / numpyro compatible? 

and incase it is useful, here is the numpyro error when using Boolean masking.

```
     98 sol = diffeqsolve(equation, solver, t0=t_eval[0], t1=t_eval[-1], dt0=0.01, y0=y0,
     99                   args=(Gamma_0,), max_steps=int(1e5), saveat=saveat,
    100                   stepsize_controller=stepsize_controller, discrete_terminating_event=event)
    102 valid_indices = ~jnp.isnan(jnp.abs(jnp.log(sol.ts))) & ~jnp.isinf(jnp.abs(jnp.log(sol.ts)))
--> 104 species_sol = jnp.array(sol.ys[:, 1:])[valid_indices].T
    105 total_abundance = jnp.sum(species_sol, axis=0)

NonConcreteBooleanIndexError: Array boolean indices must be concrete; got ShapedArray(bool[2000])
```

**Comment by snehjp2** [comment]
So, I came up with a hack-y solution where I substitute the `inf` values with random numbers drawn from a sufficiently out-of-distribution Gaussian, so that the values do not effect the particularly statistics I care about. Still open to more sophisticated fixes!

**Comment by patrick-kidger** [comment]
Yup, Boolean masking can't be used under JIT, because the output doesn't have a known shape at compile time.

Probably you want to just add `where` statements to your downstream calls. IIRC something like this is valid: `jnp.sum(x, where=jnp.isfinite(x))`.
