### ISSUE TITLE
Latent ODE

### ISSUE THREAD

**Issue by KozlovKY** [patrick-kidger/diffrax#288]
In example : https://docs.kidger.site/diffrax/examples/latent_ode/
the error is called in the function diffrax.diffeqsolve
<img width="1239" alt="Screenshot 2566-08-04 at 19 43 22" src="https://github.com/patrick-kidger/diffrax/assets/91504554/899df0ee-1f6d-47f7-bcc5-98cebf7596fd">

**Comment by KozlovKY** [comment]
<img width="1018" alt="Screenshot 2566-08-04 at 19 47 28" src="https://github.com/patrick-kidger/diffrax/assets/91504554/ef7b158e-5bcf-4a63-a02b-c363943bcdff">
The documentation says that t0,t1, dt0 are scalar, the code is arrays, it's not very clear with this one

**Comment by patrick-kidger** [comment]
This was an incompatibilty between specifically Equinox v0.10.11 and Diffrax v0.4.0.

This is fixed in Diffrax v0.4.1, which has just been released.

**Comment by KozlovKY** [comment]
Thx :)
