### ISSUE TITLE
How do you handle weights flattening for the continuous adjoint method ?

### ISSUE THREAD

**Issue by ddrous** [patrick-kidger/diffrax#289]
Hi @patrick-kidger, I hope you are doing all right.

Thanks for your efforts in building this library (along with Equinox). I've used Diffrax to do some control of Neural ODEs, and I'd like to know more about how it works. I'm interested in your [BacksolveAdjoint](https://github.com/patrick-kidger/diffrax/blob/7f30854117d46c01045c0be67435edb3cdb5db74/diffrax/adjoint.py#L678C3-L678C3) implementation of the continuous adjoint method, as described [here](https://arxiv.org/abs/1806.07366).

My question is simple, borderline stupid even LoL. So how do you __flatten__ the neural network's weights in order to solve the adjoint ODE ? Can you point me towards the function that does that please ? Follow-up if you actually do flatten the weights from the PyTree: are you not at all worried about the duplication of said weights (and the associated memory cost)?

Thanks in advance. I know you're a busy man, so anything will be useful.

Best,
@ddrous

**Comment by patrick-kidger** [comment]
Thanks for your interest! (And concern for my time :D )
`BacksolveAdjoint` doesn't flatten the weights at all. Where possible, all of my libraries try to pass around PyTrees-of-arrays, rather than single arrays, for precisely the reason you highlight: avoiding the extra time+memory overhead of the flattening.

**Comment by ddrous** [comment]
Thanks for your quick answer.
Wow, nice choice ! Thanks for this. I'm deeply amazed by what Equinox enables.
