### ISSUE TITLE
Separate events ending with DiscreteTerminatingEvent 

### ISSUE THREAD

**Issue by afcorral-desy** [patrick-kidger/diffrax#291]
In one of my projects, I am using DiscreteTerminatingEvent with a condition function and I would like to separate those trajectories that ended with the condition function being True, from those who just regularly ended because of I arrived into the final time of the propagation. I am reading the documentation of DiscreteTerminatingEvent  and it feels there is not such functionality in Diffrax. Could you confirm it? 

Thanks for your work :)

**Comment by patrick-kidger** [comment]
Given `sol = diffrax.diffeqsolve(...)`, then you can check this by looking at `sol.result`. Compare `sol.result == diffrax.RESULTS.successful` vs `sol.result == diffrax.RESULTS.discrete_terminating_event_occurred`.

FWIW this isn't very well documented at the moment. The next release will include making these result objects tidier and better-documented.
