### ISSUE TITLE
Share computation between drift and difusion

### ISSUE THREAD

**Issue by rdaems** [patrick-kidger/diffrax#309]
Hi all,

Is there an equivalent for [torchsde's `f_and_g`](https://github.com/google-research/torchsde/blob/master/DOCUMENTATION.md#providing-specialised-methods)?

Best,
Rembert

**Comment by patrick-kidger** [comment]
Yup -- just evaluate them both separately, and the compiler should be smart enough to combine them wherever possible. (Specifically, it performs common subexpression elimination (CSE).) So just something like:
```python
drift_and_diffusion = eqx.nn.MLP(...)

def drift(t, y, args):
    drift, _ = drift_and_diffusion(...)
    return drift

def diffusion(t, y, args):
    _, diffusion = drift_and_diffusion(...)
    return diffusion

terms = dfx.Multiterm(dfx.ODETerm(drift), dfx.ControlTerm(diffusion, bm))
```
should work.
