### ISSUE TITLE
Differentiating a function that returns a solution to an ODE

### ISSUE THREAD

**Issue by homerjed** [patrick-kidger/diffrax#314]
Hello,

I have a much more complicated setting in which the error

```
...
...
...
    solution = dfx.diffeqsolve(
               ^^^^^^^^^^^^^^^^
TypeError: can't apply forward-mode autodiff (jvp) to a custom_vjp function.
```

 to the code, below, arises. 

```
y0 = jnp.array([2., 3.])

def get_solution(y0):
    def f(t, y, args):
        return -y
    term = dfx.ODETerm(f)
    solver = dfx.Dopri5()
    solution = dfx.diffeqsolve(
        term, solver, t0=0, t1=1, dt0=0.1, y0=y0)
    return solution

print(jax.jacfwd(get_solution)(y0))
```
Essentially what I want to do is differentiate the following function that obtains a solution to an ODE.

What am I missing here?

Cheers : )

**Comment by patrick-kidger** [comment]
Try setting `adjoint=dfx.DirectAdjoint()` and `solver=dfx.Dopri5(scan_kind="bounded")`.

FWIW the need for this is due to JAX not supporting jvp-of-`custom_vjp`. I'd like to try and fix this up at some point.

**Comment by homerjed** [comment]
Thank you for the reply, it works!
 
 Yes, I had seen the same issue on JAX's Github where they said that too.

Thanks again.
