### ISSUE TITLE
Diffrax's num_steps in relation to SciPy.integrate.solve_ivp's nfev

### ISSUE THREAD

**Issue by ksnxr** [patrick-kidger/diffrax#315]
Many thanks for the great repo!

When I compare diffrax's results to those of solve_ivp in SciPy both using Dopri5 (RK45 in SciPy), the results seem to match, but there is a clear mismatch between Diffrax's num_steps and SciPy's nfev. nfev seems to be 6 times larger than num_steps, which happens to be the number of function evaluations per step of Dopri5 (https://en.wikipedia.org/wiki/Dormand%E2%80%93Prince_method). Could you confirm that whether this is true internally? I.e. if I compare diffrax's num_steps with scipy's nfev, should I multiply by 6? Thanks

**Comment by patrick-kidger** [comment]
Yup, that's correct.
You might still see a discrepancy of a few function evaluations -- this can be due to things like initial step size selection (makes 2 evaluations) or handling jumps (makes 1 extra evaluation that step).
