### ISSUE TITLE
Adding replicator dynamics as an example

### ISSUE THREAD

**Issue by pawel-czyz** [patrick-kidger/diffrax#329]
Dear Patrick,

I've been a long-term fan of Equinox and now I have tried Diffrax – what an excellent package! Today I was experimenting with the [replicator dynamics](https://en.wikipedia.org/wiki/Replicator_equation#Derivation_of_deterministic_and_stochastic_replicator_dynamics) and Diffrax makes integration of the SDE trajectories very convenient (it's just a few lines of code!)

I wonder what you think about having it as an example in the [Basic ODE/SDE/CDE examples](https://docs.kidger.site/diffrax/other_examples/basic-examples/) – should I submit a PR?

Best wishes,
Pawel

```
import jax.random as jrandom
import jax.numpy as jnp
from diffrax import diffeqsolve, ControlTerm, Euler, MultiTerm, ODETerm, SaveAt, VirtualBrownianTree
import jax
import matplotlib.pyplot as plt

def simplex_complete(y):
    return jnp.append(y, 1 - y.sum())

def simplex_truncate(y):
    return y[..., :-1]

dim = 3
fs = jnp.asarray([0.0, 1.0, 3.0])
noise = 0.3
sigmas = noise * jnp.ones(dim)

t0 = 0
t1 = 2.5
ts = jnp.linspace(t0, t1, 31)
x0 = jnp.asarray([9, 1, 0.5])
x0 = x0 / x0.sum()
y0 = simplex_truncate(x0)


def drift(t, y, args):
    """The drift term of the SDE.
    
    Args:
        y: shape (dim-1,)

    Returns:
        drift term for each y, shape (dim-1,)
    """
    xs = simplex_complete(y)
    phi = jnp.sum(xs * fs)
    
    square_term = jnp.sum(jnp.square(sigmas * xs))
    return y * (simplex_truncate(fs) - phi - y * jnp.square(simplex_truncate(sigmas)) + square_term)

def diffusion(t, y, args):
    """The diffusion term of the SDE of shape (K-1, K),
    i.e., maps K Wiener processes to K-1 entries
    (as the last one is determined by the others). 

    Args:
        y: shape (dim-1,)

    Returns:
        diffusion terms, matrix of shape (dim-1, dim)
    """
    k = y.shape[0] + 1
    
    term1 = (y * simplex_truncate(sigmas))[:, None] * jnp.eye(k)[:-1, :]
    term2 = jnp.outer(y, sigmas * simplex_complete(y))
    
    return term1 - term2



fig, ax = plt.subplots()
ax.set_title("$\sigma=" + f"{noise:.2f}" + "$")

for seed in range(0, 30):
    brownian_motion = VirtualBrownianTree(t0, t1, tol=1e-2, shape=(dim,), key=jrandom.PRNGKey(seed))
    terms = MultiTerm(ODETerm(drift), ControlTerm(diffusion, brownian_motion))
    solver = Euler()
    saveat = SaveAt(dense=True)

    sol = diffeqsolve(terms, solver, t0, t1, dt0=0.03, y0=y0, saveat=saveat)

    ys = jax.vmap(sol.evaluate)(ts)
    xs = jax.vmap(simplex_complete)(ys)

    for i in range(xs.shape[1]):
        ax.plot(ts, xs[:, i], alpha=0.3, color=f"C{i}", linestyle="--")
```

![image](https://github.com/patrick-kidger/diffrax/assets/26385111/12375ea2-3d44-4b2f-abe4-550216b2dcbd)

**Comment by patrick-kidger** [comment]
Hey there! Thank you for your kind words, it's great to hear about your good experience with Equinox and Diffrax.

I think on balance I'm inclined not to include an additional example. There's a fairly careful balance to be had here, and providing so much documentation sometimes makes it harder to track things down! In this case the fact that replicator dynamics are a little bit specialised means that they're probably a less-familiar choice to use a pedagogical example.

Nonetheless, I appreciate the offer! :)

**Comment by pawel-czyz** [comment]
Good point, fully understood! Closing the issue, then :slightly_smiling_face:
