### ISSUE TITLE
Question for second optimization using Diffrax (a possible error)

### ISSUE THREAD

**Issue by seishiroono** [patrick-kidger/diffrax#341]
I am trying to implement the "[shooting method](https://en.wikipedia.org/wiki/Shooting_method)" to solve a simple differential equation \(\ddot{x} = -x \) as a boundary value problem. I also need to find a solution with minimum energy.

The shooting method involves an optimization process for an initial value of \(\dot{x}(0)\). In addition, we have to optimize the initial value to find a solution with minimum energy. When I solved the differential equation using Diffrax, I encountered the following error. (Please see my code attached below.)
`ValueError: Reverse-mode differentiation does not work for lax.while_loop or lax.fori_loop with dynamic start/stop values. Try using lax.scan, or using fori_loop with static start/stop.`
On the other hand, if I implement the Euler method only with JAX, the error does not appear. So, I wonder if the error comes from the difference between Diffrax and the naive Euler implementation.

Below is my environment.
- MacOS (M2Max)
- jax: 0.4.19
- jaxlib: 0.4.19
- diffrax: 0.4.0
- jaxopt: 0.8.2

I attached my code to produce the same error.
```
import jax
import jax.numpy as jnp
from jax import grad, jit
from diffrax import diffeqsolve, Dopri8, ODETerm, SaveAt, PIDController
from jaxopt import GradientDescent

# Equation of motion
def eqm(t, y, args):
    x, x_dot = y
    return jnp.array([x_dot, -x])

# Function for solving differential equation
def solve_pendulum(initial_conditions, args, t_span, t_eval=None):
    if t_eval == None:
        t_eval = jnp.linspace(t_span[0], t_span[1], 1001)
    term = ODETerm(eqm)
    solver = Dopri8()
    saveat = SaveAt(ts=t_eval)
    stepsize_controller = PIDController(rtol=1e-7, atol=1e-7)
    solution = diffeqsolve(term, solver, t0=0, t1=10, dt0=1e-1, y0=initial_conditions, saveat=saveat, stepsize_controller=stepsize_controller, args=args)
    return solution

# Shooting method for a boundary value problem
def solve_bvp_optimal(boundary0, boundary1, initial_guess, args, t_span, t_eval=None):
    if t_eval == None:
        t_eval = jnp.linspace(t_span[0], t_span[1], 1001)

    @jit
    def cost_function(initial_guess):
        initial_conditions = jnp.hstack((jnp.array([boundary0]), initial_guess))
        solution = solve_pendulum(initial_conditions, args, t_span, t_eval)
        diff = (solution.ys[-1][0] - boundary1)**2
        return diff

    def cost_function_grad(initial_guess):
        return grad(cost_function)(initial_guess)

    def value_and_grad_function(initial_guess):
        value = cost_function(initial_guess)
        gradient = cost_function_grad(initial_guess)
        return value, gradient

    x0 = initial_guess
    opt = GradientDescent(fun=value_and_grad_function, value_and_grad=True, maxiter=1000,stepsize=0.0, decrease_factor=0.75, tol=1e-7)
    results, state = opt.run(init_params=x0)

    solution = solve_pendulum(jnp.hstack((jnp.array([boundary0]), results)), args, t_span, t_eval)
    return solution

def minimize_energy(boundary0, boundary1, initial_guess, args, t_span, t_eval=None):
    if t_eval == None:
        t_eval = jnp.linspace(t_span[0], t_span[1], 1001)

    @jit
    def cost_function(initial_guess):
        solution = solve_bvp_optimal(boundary0, boundary1, initial_guess, args, t_span, t_eval=t_eval)
        x0 = solution.ys[0][0]
        x0_dot = solution.ys[0][1]
        T = 0.5 * x0_dot**2 + 0.5*x0**2
        return T

    def cost_function_grad(initial_guess):
        return grad(cost_function, argnums=0)(initial_guess)

    def value_and_grad_function(initial_guess):
        value = cost_function(initial_guess)
        gradient = cost_function_grad(initial_guess)
        return value, gradient

    x0 = initial_guess
    opt = GradientDescent(fun=value_and_grad_function, value_and_grad=True, maxiter=1000, stepsize=0.0, decrease_factor=0.75, tol=1e-7)
    results, state = opt.run(init_params=x0)

    solution = solve_pendulum(jnp.hstack((jnp.array([boundary0]), results)), args, t_span, t_eval)
    return solution

# Given boundary
boundary = jnp.array([1, -1.])
boundary0 = boundary[0]
boundary1 = boundary[1]

# Discrete time
t_span = [0, 10]
t_eval = jnp.linspace(t_span[0], t_span[1], 1001)

solution = minimize_energy(boundary0, boundary1, jnp.array([1.]), '', t_span, t_eval)
```

Just in case, I also attach my naive Euler method. (Please note that 't_eval' is deleted, and 't_mesh' is added instead.)
```
class CustomJaxArray:
    def __init__(self, ts, ys):
        self.ts = ts
        self.ys = ys

def d_solve(initial_conditions, t_span, t_mesh):
    x0, x0dot = initial_conditions
    h = (t_span[1]-t_span[0])/t_mesh
    solution_t = jnp.linspace(t_span[0], t_span[1], t_mesh+1)

    def scan_body(params, _):
        x_t, xdot_t = params
        x1 = x_t + h*xdot_t
        x1_dot = xdot_t - h*x_t
        return (x1, x1_dot), (x1, x1_dot)
    output = jax.lax.scan(scan_body, (x0, x0dot), xs=None, length=t_mesh+1)
    solution_x = jnp.vstack([output[1][0],output[1][1]]).T
    X = CustomJaxArray(solution_t, solution_x)
    return X
```

**Comment by patrick-kidger** [comment]
Can you construct a MWE without using JAXopt? We've had difficulties with that in the past. To the point that in fact we now have our own alternative, which you may like to try as well: [Optimistix](https://github.com/patrick-kidger/optimistix).

The example on second-order optimisation [here](https://docs.kidger.site/diffrax/examples/hessian/), which makes a couple of recommendations you can try. (I'm hoping to simplify some of this at some point in the near-ish future -- need to see if we can get some changes into upstream JAX.)

Finally, just a heads-up that your `CustomJaxArray` is a bit dangerous, as it's not a [pytree](https://jax.readthedocs.io/en/latest/jax-101/05.1-pytrees.html) -- this means that JAX doesn't know how to treat it when you pass it through transforms like JIT/grad/vmap/etc. You should probably subclass [`equinox.Module`](https://docs.kidger.site/equinox/api/module/module/) instead.

**Comment by seishiroono** [comment]
After following the example and optimizing without JAXopt, the problem is now solved. Thanks for your help! Then, let me close this issue once.
