### ISSUE TITLE
FLOPS count

### ISSUE THREAD

**Issue by joglekara** [patrick-kidger/diffrax#379]
Doing one of these (https://github.com/google/jax/issues/10542) around a diffrax solve fails at 

```
    if max_steps == 1:

jax._src.traceback_util.UnfilteredStackTrace: jax.errors.TracerBoolConversionError: Attempted boolean conversion of traced array with shape bool[]..
The error occurred while tracing the function diffeqsolve at 
```

If I comment out the `max_steps` in the diffeqsolve, it works just fine but obv, the calculation is wrong! 

Any thoughts? TYIA!

**Comment by patrick-kidger** [comment]
Hmm, I'm afraid I don't know what you're referring to -- where in Diffrax is the line you quote? Can you provide a MWE?

**Comment by joglekara** [comment]
ah sorry for the crap report

```
  File "/global/homes/a/archis/.conda/envs/adept-gpu/lib/python3.10/site-packages/equinox/internal/_loop/checkpointed.py", line 229, in checkpointed_while_loop

```

**Comment by joglekara** [comment]
Ah this is probably because I'm passing in max steps as an argument and it's tripping up the tracer. I don't need that so let me try otherwise when I'm back at the desk!

**Comment by joglekara** [comment]
okay yes, it works. closing!
