### ISSUE TITLE
Passing along a distrax object in args: Mismatch custom node data

### ISSUE THREAD

**Issue by rdaems** [patrick-kidger/diffrax#383]
Hi all,

I have a value error ' Mismatch custom node data' when I want to put a [distrax](https://github.com/google-deepmind/distrax) object in args.
Minimal example:

```python
import jax
import jax.numpy as jnp
import distrax
import diffrax

def ode(t, x, args):
    p = args['p']
    return p.log_prob(x)

p = distrax.Normal(jnp.zeros(1), jnp.ones(1))
args = {'p': p}

path = diffrax.diffeqsolve(diffrax.ODETerm(ode), diffrax.Euler(), 0., 1., 0.1, 0., args=args)
```

Is there a fix for this? Or a work-around?

**Comment by patrick-kidger** [comment]
Distrax is broken:

https://github.com/patrick-kidger/equinox/issues/252

I'm afraid you'll have to use something else. :(

**Comment by patrick-kidger** [comment]
Ah, I'd love to see such an Eqx-based "Diffrax 2.0" package. That'd be excellent.

I don't have a template repo, I just copy-paste between them! Quax is probably the smallest+simplest if you want to use it as a starting point.

**Comment by rdaems** [comment]
Thanks for your comments all, I'll just use the parameters of the distributions directly and implement what I need myself.
Would indeed be a good idea to have a proper distrax package.

**Comment by lockwo** [comment]
It's still in very preliminary stages, but something you might be interested in is `distreqx`: https://github.com/lockwo/distreqx. Here you can see an example that works:

```python
import jax
import jax.numpy as jnp
from distreqx import distributions
import diffrax

def ode(t, x, args):
    p = args['p']
    return p.log_prob(x)

p = distributions.Normal(jnp.zeros(1), jnp.ones(1))
args = {'p': p}

path = diffrax.diffeqsolve(diffrax.ODETerm(ode), diffrax.Euler(), 0., 1., 0.1, jnp.array([0.]), args=args)
```

**Comment by patrick-kidger** [comment]
Oh this is awesome! Please keep us posted as this develops -- once it's further along then I'd love to advertise this more widely. (At minimum, add it to the ecosystem list.) Is the plan to produce something that is API-compatible with Distrax (including things like `Jittable`, which IIRC was their `eqx.Module`-equivalent), or something that is API-different but fills the same niche?

I am a particular fan of the name :D

**Comment by lockwo** [comment]
Will definitely let you know once I cut a first release. It is API-different but fills the same niche (early versions will pretty much have 1 to 1 feature mapping). Given the state distrax was in, I don't think a lot of (external to deepmind) applications were built on it, so I figured there wouldn't be much demand for exact API matching. Additionally, one of the key design decisions was to largely drop the concept of a "batch" from any distributions knowledge and force more explicit vmaping to give the user more control and flexibility.
