### ISSUE TITLE
Obtain dy in the solution of an ODE

### ISSUE THREAD

**Issue by MoritzMSP** [patrick-kidger/diffrax#390]
Is there an easy way to obtain $dy$ besides $y$ in the solution provided by an ODE-Solver?

I'm aware that it's possible to compute $dy$ from the defined ODE. However in my case I'm solving an equation 
$A \cdot dy=b$    where     $A = f(t, y),  b = g(t, y)$   to compute $dy$.
Construction $A$ and solving for $dy$ is computationally expensive. Therefor computing $dy$ from $y$ after solving the ODE is quite inefficient. Since $dy$ will be computed anyways to solve the ODE, I was wondering if there is a way to include $dy$ in the solution.

**Comment by patrick-kidger** [comment]
Not really, unfortunately. The places at which you choose to get outputs (as specified by `SaveAt`) need not in general correspond to the locations at which the ODE solver will make evaluations.

**Comment by MoritzMSP** [comment]
Makes sense. Thanks for the response!
