### ISSUE TITLE
Problem is too stiff to solve?

### ISSUE THREAD

**Issue by lsptrsn** [patrick-kidger/diffrax#397]
Dear Patrick,

I am trying to solve a coupled PDE system. But it doesn't solve, no matter what I try. Can you spot anything that could/should be improved? Here is the example:

import diffrax as dx
import jax
import jax.numpy as np
from jax import lax

jax.config.update("jax_enable_x64", True)

data = {
    "t_end": 35,  # Final time point for the simulation in s
    "Nt": 1000,  # Number of time steps
    "Nz": 1000,  # Number of control volumes for Finite-Volume-Method
    "T_in": 260+273.15,  # Gas temperature in K
    "X_in": 0,  # Conversion at inlet [-]
    "L_R": 2,  # Reactor length in m
    "T_scale_add": None,
    "T_scale": None,  # scaling factor for temperature
    "t_points": None,
    "D_zeta": None,
    "ATR_0": 620,
    "T_w": 240 + 273.15,  # Reactor wall temperature [K]
    }

def update_dependent_values(data):
    data["t_points"] = np.linspace(0, data["t_end"],
                                   num=data["Nt"])
    data["T_scale_add"] = data["T_in"]
    data["T_scale"] = np.max(data["T_w"]) + data["ATR_0"] - data["T_in"]
    data["zeta_mid"] = np.linspace(0, 1, 2*data["Nz"] + 1)
    data["D_zeta"] = data["zeta_mid"][2:][::2] - data["zeta_mid"][0: -1][::2]
    return data

data = update_dependent_values(data)

def PDE_sys(t, x, data):
    """Solve SINDy solution"""
    slice_size = data["Nz"]
    X = lax.dynamic_slice(x, (0,), (slice_size,))
    tau = lax.dynamic_slice(x, (slice_size,), (slice_size,))
    T = tau*data["T_scale"]+data["T_scale_add"]

    dxdt = np.zeros((2, data["Nz"]))
    dz = data["D_zeta"]*data["L_R"]

    dX_dz_0 = (X[1] - data["X_in"]) / dz[0]
    dX_dz = (X[1:-1]-X[0:-2]) / dz[1:-1]
    dX_dz_end = (X[-1] - X[-2]) / dz[-1]

    dT_dz_0 = (T[1] - data["T_in"]) / dz[0]
    dT_dz = (T[1:-1] - T[0:-2]) / dz[1:-1]
    dT_dz_end = (T[-1] - T[-2]) / dz[-1]

    d2X_dz2_0 = (X[1] - 2*X[0] + data["X_in"]) / dz[0]**2
    d2X_dz2 = (X[2:] - 2*X[1:-1] + X[:-2]) / dz[1:-1]**2
    d2X_dz2_end = (X[-1] - 2*X[-2] + X[-3]) / dz[-1]**2

    d2T_dz2_0 = (T[1] - 2*T[0] + data["T_in"]) / dz[0]**2
    d2T_dz2 = (T[2:] - 2*T[1:-1] + T[:-2]) / dz[1:-1]**2
    d2T_dz2_end = (T[-1] - 2*T[-2] + T[-3]) / dz[-1]**2

    # Equation for Conversion
    dxdt = dxdt.at[0, 0].set(-1.0141*dX_dz_0 + 3.9732*dX_dz_0*dT_dz_0 - 2.6969*X[0]*dX_dz_0 - 1.9479*X[0]**2*dX_dz_0)
    dxdt = dxdt.at[0, 1:-1].set(-1.0141*dX_dz + 3.9732*dX_dz*dT_dz - 2.6969*X[1:-1]*dX_dz - 1.9479*X[1:-1]**2*dX_dz)
    dxdt = dxdt.at[0, -1].set(-1.0141*dX_dz_end + 3.9732*dX_dz_end*dT_dz_end - 2.6969*X[-1]*dX_dz_end - 1.9479*X[-1]**2*dX_dz_end)

    # Equation for Temperature
    dTdt_0 = 1.1857*dT_dz_0 - 0.1684*dX_dz_0 + 0.2172*dX_dz_0*dT_dz_0 + 0.2457*d2X_dz2_0*d2T_dz2_0-1.1846*X[0]*dX_dz_0+0.2893*X[0]**2*dX_dz_0
    dxdt = dxdt.at[1, 0].set(dTdt_0/data["T_scale"])
    dTdt_inner = 1.1857*dT_dz - 0.1684*dX_dz + 0.2172*dX_dz*dT_dz + 0.2457*d2X_dz2*d2T_dz2-1.1846*X[1:-1]*dX_dz+0.2893*X[1:-1]**2*dX_dz
    dxdt = dxdt.at[1, 1:-1].set(dTdt_inner/data["T_scale"])
    dTdt_end = 1.1857*dT_dz_end - 0.1684*dX_dz_end + 0.2172*dX_dz_end*dT_dz_end + 0.2457*d2X_dz2_end*d2T_dz2_end-1.1846*X[-1]*dX_dz_end+0.2893*X[-1]**2*dX_dz_end
    dxdt = dxdt.at[1, -1].set(dTdt_end/data["T_scale"]) # unscale to get tau

    out = dxdt.flatten()
    return np.where(np.isnan(out), np.inf, out)
    
def solve_differential_equation(PDE_sys, data, x_init):
    """
    Solve a differential equation using a specified solver.

    Args:
        PDE_sys (dx.ODESystem): The ODE system.
        data (dict): Data containing parameters and time points.
        x_init (numpy.ndarray): Initial conditions.

    Returns:
        dx.Solution: The solution to the differential equation.
    """
    # Define the ODE term using dx.ODETerm
    term = dx.ODETerm(PDE_sys)
    # Set up a PID controller for step size control
    stepsize_controller = dx.PIDController(pcoeff=0.1, icoeff=0.3,
                                           rtol=1e-4, atol=1e-4)
    # Define when to save the results during integration
    saveat = dx.SaveAt(ts=data["t_points"])
    # root finder
    root_finder = dx.VeryChord(rtol=1e-4, atol=1e-4)
    # Set up the differential equation solver with relevant parameters
    sol = dx.diffeqsolve(term,
                         solver=dx.Kvaerno5(root_finder=root_finder),
                         # solver=dx.ImplicitEuler(root_finder=root_finder),
                         t0=0,
                         t1=data["t_end"],
                         dt0=None,
                         y0=x_init,
                         max_steps=2**30,
                         stepsize_controller=stepsize_controller,
                         saveat=saveat,
                         adjoint=dx.RecursiveCheckpointAdjoint(),
                         args=data
                         )
    return sol

t_span = np.array([0, data["t_end"]])
X_0 = np.ones((data["Nz"], 1))*1e-10
T_0 = np.ones((data["Nz"], 1))*550
tau_0 = (T_0-data["T_scale_add"])/data["T_scale"]
x_init = np.array([X_0, tau_0])
x_init = np.ravel(x_init)  # intial values as long row vector
x_init = jax.device_put(x_init)
sol = solve_differential_equation(PDE_sys, data, x_init)

**Comment by patrick-kidger** [comment]
I'm afraid general debugging of your code is outside the scope of what I can help with. :)
Good luck!
