### ISSUE TITLE
ShARK w/ additive noise

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#420]
In the documentation on SDE solvers, it says some (e.g. ShARK) should be strong order 1.5 on additive noise SDEs. But in the further documentation (https://docs.kidger.site/diffrax/devdocs/srk_example/) it seems to be about ~1.2. Is that just a numerical effect that is expected?

**Comment by patrick-kidger** [comment]
(Tagging @andyElking.)

I expect this is just a numerical oddity. This kind of messiness around the empirically-measured order is fairly common.

**Comment by andyElking** [comment]
Hi both,
That is indeed a numerical oddity, which I cannot really fix, but I made it a bit better with the PR #424. There I also explained why I think this is happening.

**Comment by lockwo** [comment]
Makes sense, thanks for that @andyElking
