### ISSUE TITLE
Custom saveat function passed negative time when integrating backwards

### ISSUE THREAD

**Issue by mathisgerdes** [patrick-kidger/diffrax#425]
Hello! I have encountered unexpected behavior, that to me looks like a bug.

Specifically, the time passed to a custom "SaveAt-fn" seems to be inverted when integrating backwards.
Consider this (trivial) example:
```python
saveat = diffrax.SaveAt(
    t1=False, 
    ts=jnp.linspace(1, 0, 5), 
    fn=lambda t, y, args: t  # save times
)

term = diffrax.ODETerm(lambda t, x, _: 1)
sol = diffrax.diffeqsolve(term, diffrax.Tsit5(), saveat=saveat, t0=1, t1=0, dt0=-1/50, y0=1.0)
```

I would expect `sol.ys` to now contain the same `ts` which I specified to save. However, instead I get negative values `[-1.  , -0.75, -0.5 , -0.25, -0.  ]`. Am I missing something obvious, or is this a bug? Is the `t` in the SaveAt `fn` different in meaning to the one appearing in the ODE term? Thanks!

Reproduced this behavior both locally and on colab, diffrax version 0.5.1.

**Comment by patrick-kidger** [comment]
Thanks for the report! Agreed that this looks like a bug.

Diffrax performs backwards-in-time integration over `t0 > t1` by solving forwards-in-time from `-t0` to `-t1`. Things are flipped around at the start and end of the solve. This means that almost all of our internals don't have to worry about the direction of the solve, which makes them much simpler to write!

We have a `direction` value, that is either `1` or `-1`, which is used to multiply timelike values where appropriate. (See `_integrate.py`.) But it looks like we missed one! We're not multiplying `t` by `direction` before calling the user-specified `SaveAt.fn`.

I can probably fix this quite quickly, but if you're interested in getting involved then I'd also be happy to take a pull request on this! (See [here](https://github.com/patrick-kidger/diffrax/blob/main/CONTRIBUTING.md)!)

**Comment by mathisgerdes** [comment]
Thanks for the swift reply! I will be busy for the next few days, but I would happily look into it afterward. If it's a quick fix for you, feel free to do it...
