### ISSUE TITLE
Resolve bear typing warning

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#433]
Whenever you run tests locally (or on PRs/github actions) you see a huge number of warnings that look like

  /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/beartype/_util/error/utilerrwarn.py:67: BeartypeDecorHintPep585DeprecationWarning: Method diffrax._solver.kl.check_return() return PEP 484 type hint typing.Tuple[jaxtyping.PyTree[typing.Union[jaxtyping.Shaped[Array, '?*control'], jaxtyping.Shaped[ndarray, '?*control'], numpy.bool_, numpy.number, bool, int, float, complex], "C"], typing.Union[jaxtyping.Float[Array, ''], jaxtyping.Float[ndarray, ''], numpy.number, float, jaxtyping.Int[Array, ''], jaxtyping.Int[ndarray, ''], int]] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
      https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
    warn(message, cls)

The number of warnings can make it difficult to interact with the tests and quickly find what is failing and it would be great to suppress (or resolve) them. Says the resolution is to change typing to bear type.typing but there may be reasons to not do that, so open to any solution.

**Comment by patrick-kidger** [comment]
I think this is a thing occuring in your `kl` branch specifically. We basically don't use `Tuple` anywhere else.

On which note: use the built-in `tuple` instead of the now-deprecated `typing.Tuple.` :)

**Comment by lockwo** [comment]
Ah I see. I've worked with a fair amount of 3.8 code recently and I think doing tuple[something] was introduced in 3.9 (earlier versions give indexing errors), so it's a force of habit to use Tuple.
