### ISSUE TITLE
Interest in new solvers

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#435]
I have two classes of solvers I'm implementing with diffrax which I thought could be good to actually just put in diffrax, but I wanted to check if there was interest in having them in diffrax before I go through the process to get them ready for a PR. 

First are some high weak order SDE solvers (Fixed step weak order 2.0 for Ito SDE solvers, e.g. SIEA etc. from https://docs.sciml.ai/DiffEqDocs/stable/solvers/sde_solve/)

Second are some diffusion model specific solvers (e.g. https://arxiv.org/abs/2105.14080). These come in two flavors: solvers that are applicable to general SDEs (or general SDEs of a certain type of noise) but perform well/better on diffusion models and solvers that are specific to (reverse) diffusion processes.

Would any subset of these be interesting to have in diffrax?

**Comment by patrick-kidger** [comment]
Definitely!

We'd need to think about how to correctly express solvers that are specific to certain diffusion processes, I suspect. Ideally these would throw an error if misused. (That's not crucial though.)

**Comment by lockwo** [comment]
Awesome, I think I have 3 open PRs right now 😅 , so that should give some time to get things into a presentable shape (and think on solver representation for specific diffusion processes)

**Comment by lockwo** [comment]
Closing to open more specific issues as we work on getting these solvers in (e.g. https://github.com/patrick-kidger/diffrax/issues/481)
