### ISSUE TITLE
SpaceTimeTimeLevy Area

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#470]
Should the abstract path class also accept a space time time levy area: https://github.com/patrick-kidger/diffrax/blob/main/diffrax/_brownian/base.py#L22?

**Comment by patrick-kidger** [comment]
I don't think so. That's not a concept that necessarily makes sense for all paths -- only really Brownian ones. Other paths might wish to represent themselves as e.g. a signature (=Magnus expansion / noncommutative exponential / ...), for example.
