### ISSUE TITLE
Stratonovich/Ito correction

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#473]
Would there be a place for a function converting Ito and stratonovich SDEs into each other? Given that the SRK methods all converge to stratonovich solutions, I found myself copying the same block of code around to reform my Ito drifts (its a quite short vjp, just:

<img width="211" alt="Screenshot 2024-07-31 at 4 45 46 PM" src="https://github.com/user-attachments/assets/c19f49c6-33c8-4ad1-977c-390a2d258472">

). I figured it could make sense to have in diffrax itself, maybe as a function that ingests ODETerms and reforms them?

**Comment by patrick-kidger** [comment]
So far I've been trying to avoid this because it introduces some pretty easy footguns around neural vector fields: as this involves a first derivative then autodiff'ing through the solve implies taking a second derivative. Meanwhile, ReLU is only first-differentiable, so I suspect things would probably go wrong silently.

I think I'm probably going to label this one as out-of-scope, I'm afraid.

**Comment by lockwo** [comment]
coming back to this with a thought I had: wouldn't neural SDE people never use it? Like if you are parameterizing the drift and diffusion, usually the stratonovich/ito correction is ignored (since you can just learn whatever).  (all good it is out of scope, I was just curious since you have expertise on this) Are there cases in Neural SDEs where you would want to convert Ito/Strato during training?

**Comment by patrick-kidger** [comment]
You are entirely correct :) Indeed we argue for using Stratonovich over Ito in one of my old papers!

**Comment by lockwo** [comment]
Is this concern over derivatives of derivatives also the primary reason there aren't any Taylor schemes implemented in diffrax?

**Comment by patrick-kidger** [comment]
That's a valid concern, but it's mostly just that I've yet to really be convinced of Taylor schemes, so I've never invested the time to implement them.

Taylor expansions are pretty much the worst possible polynomial approximation to a function over an interval. To be precise they differ by a factor of 2^n from the best possible polynomial approximation of order n, which is quite a big constant to place in front of your truncation error!
