### ISSUE TITLE
How to use Jax debug tools inside ODE/SDE/CDE Terms?

### ISSUE THREAD

**Issue by qtomcatq** [patrick-kidger/diffrax#482]
Hi, I'm new to this software, so this question might seem obvious to some. I'm trying to debug the Terms of Neural ODE/SDE/CDE in Diffrax with jax.debug.breakpoint(). For example, we have the code of Term of Neural ODE in neural_ode.ipynb (in examples folder): 

```
class Func(eqx.Module):
    mlp: eqx.nn.MLP

    def __init__(self, data_size, width_size, depth, *, key, **kwargs):
        super().__init__(**kwargs)
        self.mlp = eqx.nn.MLP(
            in_size=data_size,
            out_size=data_size,
            width_size=width_size,
            depth=depth,
            activation=jnn.softplus,
            key=key,
        )

    def __call__(self, t, y, args):
        jax.debug.breakpoint() 
        return self.mlp(y)
```

it works fine here, but if you add an error like this (wrong output dimension): 

`class Func(eqx.Module):
    mlp: eqx.nn.MLP

    def __init__(self, data_size, width_size, depth, *, key, **kwargs):
        super().__init__(**kwargs)
        self.mlp = eqx.nn.MLP(
            in_size=data_size,
            out_size=data_size,
            width_size=width_size,
            depth=depth,
            activation=jnn.softplus,
            key=key,
        )

    def __call__(self, t, y, args):
        #pdb.set_trace()
        jax.debug.breakpoint()
        return self.mlp(y[0:-1])      #wrong output dimension
`

it throws the error before entering the debugger. However the Python function pdb.set_trace() acts as a "true debugger", pdb works regardless of the fact if the code is correct or not after breakpomt. 

What could be the solution to this? I've tried to disable jit, it didn't help.

**Comment by patrick-kidger** [comment]
If you're trying to inspect a shape error then you probably want the normal builtin `breakpoint()` (which by default just calls `import pdb; pdb.set_trace()`.

The first thing JAX does is to run your Python program with 'tracers', that record everything that happens to them. After the Python program has been completely traced, then this computation graph is compiled and ran. (And your Python code is never touched again.)

So the normal `breakpoint()` is what you want if you're getting an error during that first tracing step. You can inspect the tracers themeslves -- in this case probably the `.shape` is the thing you'd like to check.

Meanwhile `jax.debug.breakpoint()` is what triggers during the actual runtime of your code -- after it has been compiled and when actual values (not just tracers) are available.

---

If this all seems a little confusing at first, then this is actually exactly the same thing you see in any compiled languages: first we have compilation, and then we have runtime. In this case, we're using Python to specify what we should compile.

**Comment by qtomcatq** [comment]
Thank you!

**Comment by qtomcatq** [comment]
Thank you!
