### ISSUE TITLE
Parallel Testing

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#486]
The tests take a long time to run (hours), but each set of tests have no communication and can be parallelized. Using pytest parallelism you can pretty easily get near linear speedups from parallelism (via https://github.com/pytest-dev/pytest-xdist). I use it locally to help accelerate running the tests, and I think it could help accelerate the tests that run on PRs. Even the default runners 4 CPUs could be faster (and larger runners would increase this)

**Comment by patrick-kidger** [comment]
That sounds reasonable to me! I think you know the drill, happy to see a PR on this!

**Comment by lockwo** [comment]
Looks like it's ooming, will probably only work w/ larger runners (https://github.com/patrick-kidger/diffrax/pull/487).
