### ISSUE TITLE
Levy Area documentation

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#491]
The levy area documentation has a lot of extra stuff that I think is a bug in displaying. 

<img width="1069" alt="Screenshot 2024-08-16 at 1 47 30 PM" src="https://github.com/user-attachments/assets/7a4fdbec-f10f-43e4-9c02-e3b8d0692a76">

I know the drill, PR it is ;).

PS sorry for spamming you with issues, just wanted to get them all made so I don't forget

**Comment by patrick-kidger** [comment]
Haha!
Thank you :)

I think in this case it should be a simple matter of adding a `selection: members: ...` like every other class.
