### ISSUE TITLE
Add weak order to solvers?

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#497]
strong order is a attribute of the SDE solvers, but they also possess a weak order. Is there any reason not to include weak order as well (or should it wait until the first weak solver is going in)?

**Comment by patrick-kidger** [comment]
I left these off mostly because I didn't feel like tracking them down for every solver! A lot of these just aren't well-documented.

That aside it's just not that useful -- strong order is used in the theory of adaptive stepping, so it is needed programmatically. The same isn't true for weak.
