### ISSUE TITLE
Different step sizes within batch?

### ISSUE THREAD

**Issue by jucor** [patrick-kidger/diffrax#500]
Dear @patrick-kidger 

Is there any way that diffrax would support using different timesteps within a batch, like https://github.com/martenlienen/torchode offers?

For context:  I need to evaluate a 1-dimensional ODE on a fixed time grid but with 1000,000 different parameters, while using a Sequential Monte Carlo sampler on a ODE-based likelihood.

The best way I've found with diffrax to parallelize those calls to the ODE is to make this a single 100,000-dimensional ODE, where each dimension y[i] corresponds to one value of the parameters and for each dimension `i`,  `dydt[i]` only relying on `y[i]` (if it were linear we'd say it's a diagonal matrix, but it's nonlinear :) ).

But of course some parameters make for a more difficult ODE than others (sometimes even NaN-ning), and this thus impacts the step-size for all dimensions, making it slower and less stable.

Maybe I could just use https://github.com/martenlienen/torchode , which is in the Torch ecosystem, with  would seem to promise the solution, but it's in the torch ecosystem, and my sampler is in Jax. Maybe I could mix and match, though?

Thanks for letting me know if this heteregoneous-timesteps-within-a-batch is possible, and if not, if it's on the roadmap at all!

**Comment by patrick-kidger** [comment]
Indeed Diffrax supports this already via `vmap` :)

**Comment by jucor** [comment]
Wowser, this is *terrific*. Can't believe how simple it is, yet it works :) Thanks a lot!
