### ISSUE TITLE
impure sub function inside of `diffeqsolve()` ? 

### ISSUE THREAD

**Issue by thibmonsel** [patrick-kidger/diffrax#509]
Hi Patrick,

I was wondering if `_allocate_output()` could be an impure function, why ? 

- In L1201 `struct` refers to the variables `y0` and `t0`. 
Would these variables be out of scope for the function `_allocate_output()` ?
`struct = eqx.filter_eval_shape(subsaveat.fn, t0, y0, args)`

https://github.com/patrick-kidger/diffrax/blob/ada5229c46ed041b30090b969f9943082e5300d6/diffrax/_integrate.py#L1181

**Comment by patrick-kidger** [comment]
These closed-over values ae provided as inputs to the `diffeqsolve` function. There's nothing wrong with closing over values in JAX! It's basically the same as writing
```python
def some_module_function(t0, y0, ...):
    ...

def diffeqsolve(t0, y0, ...):
    _allocate_output = functools.partial(some_module_function, t0, y0)
    ...
```

**Comment by thibmonsel** [comment]
Ok thanks for the input, but if these closed-over values are transformed afterwards this could maybe be problematic ? 

In my particular setup of integrating a DDE and by setting `EQX_ON_ERROR=breakpoint`
To my understanding, the error log below would mean that `t0` is a leaked tracer : 

```
Exception: Leaked trace MainTrace(3,DynamicJaxprTrace). Leaked tracer(s):
...
Traced<ShapedArray(float32[])>with<DynamicJaxprTrace(level=3/0)>
This DynamicJaxprTracer was created on line /home/monsel/Desktop/dev_diffrax/diffrax/diffrax/_integrate.py:1210 (diffeqsolve)
<DynamicJaxprTracer 128368101046400> is referred to by <function 128368112440448> (_check_subsaveat_ts) closed-over variable t0
...
```

https://github.com/thibmonsel/diffrax/blob/e49721cdde037124395bf4ac6a499885fc0fc14d/diffrax/_integrate.py#L1210

**Comment by patrick-kidger** [comment]
The closed-over values will be captured at the moment their enclosing function is traced. In our case that's the line immediately afterwards:

https://github.com/patrick-kidger/diffrax/blob/ada5229c46ed041b30090b969f9943082e5300d6/diffrax/_integrate.py#L1209

There's actually nothing JAX-specific happening here. We have a function that closes over a variable, and when call that function, the current value of that closed-over variable is used.
