### ISSUE TITLE
Error when used in gradient optimization with accumulation and diffrax.PIDController.

### ISSUE THREAD

**Issue by juehang** [patrick-kidger/diffrax#521]
When a neural ODE with diffrax.PIDController is trained using `optax`, wrapping the optimizer with `optax.MultiSteps` leads to the following error:
```
TypeError: Value <function rms_norm at 0x7f554c241990> with type <class 'function'> is not a valid JAX type
```

This does not occur is `ConstantStepSize` is used as the step size controller.

**Comment by lockwo** [comment]
Possibly related issue: https://github.com/patrick-kidger/equinox/issues/853

**Comment by patrick-kidger** [comment]
See also https://docs.kidger.site/equinox/faq/#optax-throwing-a-typeerror . Optax accepts a pytree-of-arrays. Make sure you provide it only the arrays you want to optimize, not the non-array parts of the model pytree.

**Comment by juehang** [comment]
Thanks for the replies, indeed that was the issue and the @lockwo 's suggestion on https://github.com/patrick-kidger/equinox/issues/853 fixed it.
