### ISSUE TITLE
diffeqsolve terms gives value error from within jax.vmap

### ISSUE THREAD

**Issue by srossell** [patrick-kidger/diffrax#538]
Hi,

Thanks for your amazing work!

I have a simple system of odes, which I can solve with diffeqsolve without problems. But when I try to solve it varying parameters and initial conditions within vmap, I get an error:

`
ValueError: `terms` must be a PyTree of `AbstractTerms` (such as `ODETerm`), with structure <class 'diffrax._term.AbstractTerm'>`

My script below fails on the last line:

```python
from diffrax import diffeqsolve, ODETerm, Tsit5
import jax
import jax.numpy as jnp


def odes(t, y, p):
    vmax, km = p
    return [-y[1] * vmax * y[0] / (km + y[0]), y[1] * 0.09 * vmax * y[0] / (km + y[0])]

solver = Tsit5()
term = ODETerm(odes)

# Generate initial conditions
y0 = [10.0, 0.2]
p = [10.0, 5.0]
y0_array = jnp.array([jnp.linspace(6, 12, 7), jnp.linspace(0.1, 0.7, 7)])

p_array = jnp.array([jnp.linspace(8, 12, 7), jnp.linspace(4, 6, 7)])

# One simulation
onesol = diffeqsolve(term, solver, 0, 120, 0.1, y0, p)

vect_solve_ode = jax.vmap(
    diffeqsolve,
    in_axes=[None, None, None, None, None, 1, 1],
)
sols = vect_solve_ode(term, solver, 0, 120, 0.1, y0_array, p_array)
```

Is my variable "term" somehow changing when invoked with vmap? 

I hope you can point me out to the right direction.

Very best wishes,

Sergio

**Comment by johannahaffner** [comment]
Hi Sergio, 

The issue is that you are defining your single `y0` as a list of values, but then try to vmap this over an array of values `y0_array`. Since the output of your ODE is a list, the types no longer match and diffrax will throw an error. 

You do not get the same problem with the parameters, since the list and array can both be unpacked in the same way. 

Here is the updated code:

```python
import jax
import jax.numpy as jnp
from diffrax import diffeqsolve, ODETerm, Tsit5


def odes(t, y, p):
    vmax, km = p
    d_y0 = -y[1] * vmax * y[0] / (km + y[0])
    d_y1 = y[1] * 0.09 * vmax * y[0] / (km + y[0])
    return jnp.array([d_y0, d_y1])

solver = Tsit5()
term = ODETerm(odes)

# Generate initial conditions
y0 = jnp.array([10.0, 0.2])
p = [10.0, 5.0]
y0_array = jnp.array([jnp.linspace(6, 12, 7), jnp.linspace(0.1, 0.7, 7)])

p_array = jnp.array([jnp.linspace(8, 12, 7), jnp.linspace(4, 6, 7)])

# One simulation
onesol = diffeqsolve(term, solver, 0, 120, 0.1, y0, p)

vect_solve_ode = jax.vmap(
    diffeqsolve,
    in_axes=[None, None, None, None, None, 1, 1],
)
sols = vect_solve_ode(term, solver, 0, 120, 0.1, y0_array, p_array)
```

**Comment by srossell** [comment]
Thank you Johanna,

Your suggested code update solves the issue, and let me understand what I was doing wrong.

Thanks again and very best wishes,

Sergio

**Comment by johannahaffner** [comment]
Great!

**Comment by jecampagne** [comment]
Hi, what a nice soft ! Thanks a lot.

I have a question related to the vmapping of `diffeqsolve`. I have tried the above scenario but it fails.
I have a unique starting "point" (`M0` below) a 2 sets of 11-parameters (`a...q` variables below).  

```python
def vector_field(t, M, args):
    x,y,z,w = M
    ....
   return jnp.array([d_x, d_y, d_z, d_w])

term = ODETerm(vector_field)
solver = Dopri5() #Tsit5() 
t0 = 0.
t1 = 10000
dt0 = 1e-2


# init value
x0 = jnp.array([0.01]*2)
y0 = jnp.array([1.0]*2)
z0 = jnp.array([0.01]*2)
w0 = jnp.array([1.0]*2)


M0 = jnp.array([x0,y0,z0,w0])

# init a,b,c,d,lam,mu,g,h,f,p,q 
a = jnp.array([1.0,1.1])
b = jnp.array([2.0,2.2])
c = jnp.array([1.0,1.1])
d = jnp.array([0.5,0.55])
lam = jnp.array([2.0,2.2])
mu = jnp.array([2.0,2.2])
g = jnp.array([0.4,0.44])
h = jnp.array([1.0,1.1])
f = jnp.array([0.0, 0.0])
p = jnp.array([1.0, 1.1])
q = jnp.array([2.0, 2.2])
params= jnp.array([a,b,c,d,lam,mu,g,h,f,p,q])
saveat = SaveAt(ts=jnp.linspace(t0, t1, 10000))

vect_solve_ode = jax.vmap(
    diffeqsolve,
    in_axes=[None, None, None, None, None, 1, 1],
)

sols = vect_solve_ode(term, solver, t0, t1, dt0, M0, params, saveat=saveat, max_steps=100_000, throw=False)

```
I get this error message
```
ValueError: vmap was requested to map its argument along axis 0, which implies that its rank should be at least 1, but is only 0 (its shape is ())
```

may be it is clear msg but I cannot fix it yet. Any help is welcome.
Thanks

**Comment by jecampagne** [comment]
Ho! my bad. After writing this question I found the solution. I let it as it may be useful for somebody else. The
problem is just due to the extra arguments of the `diffeqsolve`. The trick is to use a `partial`-ized version.
```python
from functools import partial
my_diffeqsolve = partial(diffeqsolve, saveat=saveat, max_steps=100_000, throw=False)

vect_solve_ode = jax.vmap(
    my_diffeqsolve,
    in_axes=[None, None, None, None, None, 1, 1],
)

```

**Comment by johannahaffner** [comment]
Yes, that is correct! You want to use jit at the outermost level - `jit(vmap)` is much more efficient that `vmap(jit)`. 

If your function inputs include things that are not pytrees of arrays you might also be interested in using `eqx.filter_jit` (more [here](https://docs.kidger.site/equinox/api/transformations/)).

**Comment by johannahaffner** [comment]
That is not quite right yet - `in_axes` should be a tuple, not a list, and you should use Python-style zero-based indexing - if I got this correct from a glance at your code then your arrays are actually one-dimensional, meaning that they have shape `(n,)` and you can only map them over their first axis.

Another pattern that might be helpful here is `jit(lambda x: f(x, y))(some_x)` since you seem to have many non-mapped inputs.

**Comment by johannahaffner** [comment]
PS: most of my personal use-cases don't require GPUs, and if your problems are not particularly high-dimensional then the overhead may outweigh your actual problem.

**Comment by jecampagne** [comment]
hi @johannahaffner , thanks for your advises. To be more explicit, may I ask you to give me an example of the use of
```
Another pattern that might be helpful here is jit(lambda x: f(x, y))(some_x) since you seem to have many non-mapped inputs.
```
in my case? That  would be nice.

**Comment by jecampagne** [comment]
Well, it seems like a `partial`, no? SHould I have use a extended version of  
```python
my_diffeqsolve = partial(diffeqsolve, terms=term, solver= solver, t0=t0, t1=t1,dt0=dt0, saveat=saveat, max_steps=100_000, throw=False)

vect_solve_ode = eqx.filter_jit(jax.vmap(
    my_diffeqsolve,
    in_axes=(1, 1),

```

**Comment by johannahaffner** [comment]
Nice!
