### ISSUE TITLE
Clarity in the ULD example

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#543]
In the ULD example it is claimed "Note that unlike ODE solvers which can have orders of 5 or even higher, very few types of SDEs permit solvers with a strong order greater than 1/2", but isn't Milstein strong order 1 on all SDEs (KP pg. 345)? (granted diffrax only implements the commutative noise variant)

**Comment by patrick-kidger** [comment]
If you don't have commutative noise then you need Levy Area approximations. (These are a can of worms and at least right now we don't do these in Diffrax.)

The impossibility of doing better than strong-order-0.5 (without either special noise structure or approximations of higher terms) is a famous result from Cameron and Clark back in 1980: https://link.springer.com/chapter/10.1007/BFb0004007 .

**Comment by lockwo** [comment]
I see, resolved this with some further offline discussions with Frank (to consolidate my point, was just that these approximations exist e.g. https://github.com/stochastics-uni-luebeck/LevyArea.jl, so assuming you can do them in theory isn't crazy, but in practice can certainly be painful).
