### ISSUE TITLE
[packaging] Could the source please be tagged for version 0.0.2

### ISSUE THREAD

**Issue by dhirschfeld** [patrick-kidger/diffrax#63]
It makes it easier to understand exactly what code you're running if you can reference the tag in GitHub.
* https://pypi.org/project/diffrax/0.0.2/

**Comment by dhirschfeld** [comment]
Maybe it's tagged locally but the tag wasn't pushed to GitHub with `git push origin 0.0.2`?

I've done that enough that I configure my `git` with:
```
git config --global push.followTags true
```

Can't find any great refs offhand but [this](https://vivaxyblog.github.io/2019/08/02/git-tag-and-push-git-tag.html) article gets the gist across.

**Comment by patrick-kidger** [comment]
Ah yep, it was tagged locally but not pushed here.

I hope haven't committed (hah) too deep a heresy by using lightweight tags rather than annotated tags.

**Comment by dhirschfeld** [comment]
> *I hope haven't committed (hah) too deep a heresy by using lightweight tags rather than annotated tags.*

😳 

..haha, just kidding! Though annotated tags *do* have benefits around reproducibility & provenance so  I use & recommend them. It's a shame the GitHub UI creates lightweight tags 🙄 
https://github.com/github/feedback/discussions/4924

**Comment by dhirschfeld** [comment]
Closing as `FIXED`, thanks @patrick-kidger!

I'll try and make time to add a CF package shortly. Happy to do so if you don't beat me to it...

**Comment by dhirschfeld** [comment]
All of our tooling uses `conda` (`mamba` actually) so it's awkward to use `pip` and we will need a `conda` package if we're to deploy it.

> I find myself just doing `conda create ...; pip install` ... most of the time.

There was a time when `pip` and `conda` would stomp all over each other and that would've been a recipe for broken packages with remnants of different versions lying about. I think they play nicer together now, but I still don't trust that one or the other won't just partially overwrite existing packages which is a recipe for undefined behaviour.

We don't use `pip` because historically it hasn't had a dependency solver so there was no guarantee the environments it creates actually adhere to the specified constraints of the packages. Presumably, the authors of the packages specified those constraints for a reason so IMO, creating a complex analytics environment using `pip` was again a recipe for undefined behaviour. 

`pip` was ok at creating an initial environment (though I gather it still had issues with transitive dependencies) but if you installed anything after the fact it would blatantly ignore the version constraints of the packages in the environment. To work around this, the received wisdom was that you shouldn't update environments but should instead create new environments for all projects. That's all well and good, but IME with less experienced developers (e.g. analysts) that ~never happens in practice. Analysts need a tool that helps prevent them from shooting themselves in the head.

I worry about silent failures as I have experienced (many times) our test-suite breaking, not with loud exceptions but just incorrect results after upgrading dependencies. Simply adhering to the specified constraints can't prevent that from happening because new packages can break previously working code however, IMO, it's an absolutely necessary first line of defence against silent failures. Your test suite should check that new versions of dependencies don't (silent) break your code, but again, less experienced developers, such as analysts, are those least likely to have comprehensive test coverage.

`pip` now does have a dependency resolver, but, not being a `pip` user I can't really comment on it. I do however think that after nearly a decade's experience and battle-testing in production that `conda`s' solver is likely to be more robust than `pip`'s.

Even if `pip` and `conda` were now equally good at creating (and updating) complex environments `pip` wheels are IMO a very complex but ultimately inferior solution to the problem which `conda` solves properly... because it was exactly designed to (I highly recommend reading this [blog post](https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/) on the origin of `conda`).

For information on the complexity of correctly building wheels I recommend reading Uwe's blog post:
https://www.xhochy.com/2019/09/15/how-we-build-apache-arrows-manylinux-wheels.html. I also think [CFED-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md) is required reading. TL;DR; all wheels contain their statically linked dependencies so two packages using the same dependencies will have independent copies, not just on disk but in memory also. This increases the size of your containers which makes them slower to serve and it also increases their memory requirements which makes them more costly to run.

So, those are my reasons for choosing ~~`conda`~~`mamba`! 


> found the documentation to be rather opaque. 

Yeah, the documentation isn't great. Fortunately, the community on gitter is pretty helpful:
https://gitter.im/conda-forge/conda-forge.github.io

My go-to for understanding the latest recommendations for writing a conda recipe is to check out the example recipe in `conda-forge/staged-recipes`:
https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml

Since I'll need a `conda` package I'm happy to open a PR there to add `diffrax` to CF.

> is it possible to have CF automatically track PyPI releases?

Once on CF their bot will open a PR for any new packages published on `pypi` so it's a *mostly* automated process. It won't however update any deps (though there's some [new tooling to do so](https://twitter.com/mdtrevisani/status/1487894867799859201) I believe). For now though deps may have to be manually updated before merging the bot's PR.

**Comment by patrick-kidger** [comment]
Haha, you clearly have strong opinions about this! FWIW I've also had the experience of tearing my hair out when I've run into the limitations of `pip` before.

Okey dokey, go ahead and create the CF release. (I imagine you'll have to do one for [Equinox](https://github.com/patrick-kidger/equinox) as well?) At least for the time being CF won't be a channel I maintain/espouse myself though, just to manage the amount of maintenace work I have to do.

**Comment by dhirschfeld** [comment]
> Haha, you clearly have strong opinions about this! 

Ha, yep I do - you didn't know what can of worms you were opening! 😆 

> At least for the time being CF won't be a channel I maintain/espouse myself though

That's fine - I'm happy to review & merge the bot PRs whenever a new release is published and you can always add yourself as a maintainer whenever you'd like in future.

> I imagine you'll have to do one for `equinox` as well?

Yep - I'll have to get all the deps on CF so I'll apply the same policy there - I won't add you as a maintainer to start with but I'll be happy to do so if you ever want in future.

Being a "maintainer" on a CF feedstock just means you're added to the team so have merge rights. It does mean you'll get emailed for new PRs/issues so it does involve some extra maintenance overhead.

**Comment by patrick-kidger** [comment]
Alright, sounds good!

**Comment by dhirschfeld** [comment]
FYI: The latest and greatest are now available from `conda-forge`
* https://github.com/conda-forge/equinox-feedstock
* https://github.com/conda-forge/diffrax-feedstock

**Comment by dhirschfeld** [comment]
Seems to work AFAICT!

**Comment by patrick-kidger** [comment]
Hurrah!
