### ISSUE TITLE
`t1` is not considered static?

### ISSUE THREAD

**Issue by pharringtonp19** [patrick-kidger/diffrax#97]
I am surprised (although perhaps I should not be) that we don't have to mark `t1` as a static argument. Am I missing something obvious? -- thanks!

```
import jax 
from diffrax import diffeqsolve, ODETerm, Dopri5, SaveAt, PIDController
from einops import rearrange
import jax.numpy as jnp

def f(t, y, args):
    return -y 

term = ODETerm(f)
solver = Dopri5()
stepsize_controller = PIDController(rtol=1e-5, atol=1e-5)

@jax.jit
def ivp(t1, y0):
  return diffeqsolve(term, solver, t0=0, t1=t1, dt0=0.1, y0=y0, saveat=SaveAt(t1=True), stepsize_controller=stepsize_controller).ys
```

**Comment by patrick-kidger** [comment]
You're not missing anything. `t1` can indeed be traced just fine!

Even better than that: if `t1` does happen to be static, and so are `t0` and `dt0`, and you're using a constant step size solver, then it is possible to compile in all of this information and emit more efficient code by using `ConstantStepSize(compile_steps=True)`.

**Comment by pharringtonp19** [comment]
@patrick-kidger Thanks for the response and the additional tip! Will definitely play around with this -- much appreciated
